### ISSUE TITLE
Investigate qemu for validating playbooks on Linux on ppc64le/s390x

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1059]
See e.g.
- Official qemu ppc64 info at https://wiki.qemu.org/Documentation/Platforms/POWER
- https://djanotes.blogspot.com/2018/09/running-ubuntu-ppc64le-virtual-machine.html
- https://wiki.alpinelinux.org/wiki/Ppc64le
- https://stackoverflow.com/questions/53259899/is-it-possible-to-run-vm-with-ppc64le-architecture-on-a-host-machine-with-x86-64

**Comment by Willsparker** [comment]
I had a look at ci.adoptopenjdk.net, and it appears we need the following iso images, if only looking at the ppc64le, s390x and arm architectures: 

| U16 | ppc64le, s390x, armv7, armv8 |
|-----|-------------------------------|
| U18 | ppc64le, armv8               |
| C7  | ppc64le, armv8               |

Am I missing any?

**Comment by sxa555** [comment]
I think that since we have good coverage across distributions on x64 I'm happy with just going for just one on each architecture for now. Let's go Ubuntu18.04 where available, and Ubuntu16.04 otherwise for now.

**Comment by Willsparker** [comment]
Okay - unfortunately the `armv7l` architecture is available for either Ubuntu's, so I'm looking at Raspbian instead , as per your suggestion.

**Comment by Willsparker** [comment]
https://worthdoingbadly.com/aixqemu/ 

Apparently AIX is possible too!

**Comment by Willsparker** [comment]
According to https://superuser.com/questions/297162/how-to-access-internet-from-qemu qemu is setup to access the internet by default.
I've confirmed this by running `qemu-system-ppc64 -M pseries -m 1024 -cdrom U18-ppc64el.iso -boot d -hda  U18-ppc66le.dsk `
Once running through the installation and then rebooting the system from the disk (by removing the `-cdrom` and `-boot` option), I was able to run `git clone https://github.com/adoptopenjdk/openjdk-infrastructure` , `sudo apt install ansible` and begin running the playbook with the following output : 

![Screenshot 2020-01-21 at 10 28 30](https://user-images.githubusercontent.com/52783864/72797320-ce961980-3c38-11ea-87bd-0cfbab9851a7.png)

**Comment by Willsparker** [comment]
I have also attempted to do the same with `s390x` and `arm64` systems, however, according to https://gmplib.org/~tege/qemu.html , it appears that the qemu commands for different architectures require different things to boot the system - i.e. `qemu-system-ppc64` can boot the system with an `.iso` image, however the `qemu-system-aarch64` command requires a separate `kernel` and `initrd` files. 

I was able to follow this tutorial : https://translatedcode.wordpress.com/2017/07/24/installing-debian-on-qemus-64-bit-arm-virt-board/ to start an `aarch64` system running debian8, as an example of running a system using the `kernel` and `initrd` files instead of an ISO.

**Comment by Willsparker** [comment]
https://astr0baby.wordpress.com/2019/05/09/testing-bleeding-edge-ubuntu-server-19-10-s390x-in-qemu/ 

^ An example of how to get the kernel and initrd files from an .iso file

**Comment by Willsparker** [comment]
https://unix.stackexchange.com/questions/124681/how-to-ssh-from-host-to-guest-using-qemu
^ Found a very easy way to connect to the hosts via ssh - Adding this into the `qemu-system-..` commands : `-net user,hostfwd=tcp::10022-:22 -net nic`
This creates a basic network interface card for the machine, and then forwards the `10022` port from the host machine to port `22` on the guest machine. Therefore, it can be accessed (and have remote commands run) via: 
`ssh username@localhost -p10022 $COMMAND` 
Works on the Ubuntu1804-s390x VM I created to begin testing this.

**Comment by Willsparker** [comment]
I've been able to get ansible working with the qemu vm by using the command: 
`ansible all -i "localhost:10022," --private-key=id_rsa -u username -m raw -a "uname -a"`, after having copied the public ssh key via `ssh-copy-id -i id_rsa.pub user@localhost -p 10022`

This can be automated by using `expect` scripts to give the Qemu VM the password to the `username` user: 
```
#!/usr/local/bin/expect -f
set timeout 20
set cmd [lrange $argv 1 end]
set password [lindex $argv 0]
eval spawn $cmd
expect "assword:"
send "$password\r";
interact
```
And in the bash script : `./expect_script.sh password ssh-copy-id -i id_rsa.pub username@localhost -p 10022`

**Comment by Willsparker** [comment]
I've been able to create and install Ubuntu on 2 machines for s390x and ppc64. They both have a 15G of disk space, and have the same user credentials. 
Currently in the process of doing the same for U18-armv8.

**Comment by Willsparker** [comment]
Scratch that - I can get as far as it trying to detect the CD-rom, however it won't detect the iso. @sxa555 Do you mind if we use Debian Stretch or raspbian for armv8 emulation? Following the Debian-on-Qemu's-virt-board tutorial above worked before whilst I was testing.

**Comment by sxa555** [comment]
Happy with either of those if you can make it work

**Comment by Willsparker** [comment]
I have been able to get the `armv64` disk running with Debian Stretch on it. Unfortunately the tutorial that I linked to above requires it to stores the kernel and initrd files in addition to the disk. Though this isn't a massive issue, having one architecture different to the other two complicates a script to automate playbook testing on them.
This disk has the same user configuration on it as the other two, and also has 15GB of disk space - however it has a non-LVM file system as this stops the VM from being able to boot.

**Comment by sxa555** [comment]
Have created a jenkins job https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Will-QEMUplaybookTest/ which Will has access to (it's a copy of the Vagrant one for now) which can be used to test this now that the script at https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1119 has been developed. The https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/vagrant.yml playbook will also need to be updated to include the installation of qemu.

**Comment by Willsparker** [comment]
I've been able to get the playbook running on a `ppc64le` architecture VM: https://ci.adoptopenjdk.net/job/Will-QEMUplaybookTest/ARCHITECTURE=ppc64le,label=infra-vagrant-1/6/console 

It seems `s390x` still isn't working (I hypothesise because the VM isn't booted in time to carry out all the ssh commands, so an increase in `sleep` may be needed)

I've stopped using `expect` and instead use `ssh_pass` as it seems running a script through Jenkins stops `expect` from working : https://stackoverflow.com/questions/28478611/jenkins-not-waiting-on-call-to-a-bash-script-with-expect/40087426#40087426
As both `expect` or `sshpass` would need to be added to the `vagrant.yml` playbook anyway, I've opted for using `sshpass` instead.

**Comment by Willsparker** [comment]
I ran the s390x machine on the `infra-vagrant-1` node without sending it to the background, and the machine isn't booting due to this error message:
```
qemu-system-s390x: Initialization of device s390-ipl failed: could not find stage1 bootloader
```
Which is reported here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832897
I checked, and `apt install qemu` puts quite an old version of qemu on the system : 
```
$ qemu-system-s390x --version
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.21)
```
as opposed to on my mac which is version `4.2.0`.
Therefore, I feel the best solution is to instead build qemu 4.2.0 on the machines, and put it in the `..playbooks/vagrant.yml` playbook.

**Comment by sxa555** [comment]
Title adjustment to de-scope this to exclude aarch64 for now

**Comment by sxa555** [comment]
We have compressed disk image files in /qemu_base_images on `infra-vagrant-1` which can be extracted with e.g. `xz -cd /qemu_base_images/PPC64LE.dsk.xz > PPC64LE.dsk`

**Comment by Willsparker** [comment]
The PR above is now ready to be reviewed, that should hopefully close this issue.

Though not relevant to this specific issue, on Friday I was attempting to run a qemu machine emulating `sparc64` with Solaris 10(u11). The furthest I was able to get to was following the tutorial here : 
https://tyom.blogspot.com/2016/10/qemu-sun4vniagara-target-went-public.html   and 
https://wiki.qemu.org/Documentation/Platforms/SPARC (the last command in the `Compatibility` section)

And while this machine did boot, it had no network adapter to connect to the internet, despite attempts to put adaptors on via `-net nic,model=ne2k_pci -net user` and changing the various models. All would result in the machine booting, sans the network adaptor  with a warning stating that machine doesn't support that adaptor.

**Comment by sxa555** [comment]
Complete and running at https://ci.adoptopenjdk.net/job/Will-QEMUplaybookTest/ - closing
