### ISSUE TITLE
sanity.system tests fail on test-packet-x64-windows-2012r2-1 due to missing perl

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1071]
Example failing output

https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_x86-64_windows/106/

The tests require a Windows perl port (not cygwin perl) to execute correctly.  The test failed to find one on test-packet-x64-windows-2012r2-1
```
06:55:01  ../systemtest.mk:31: Running under cygwin, looking for Windows perl on path
06:55:01  ../systemtest.mk:34: *** Unable to find Windows perl e.g. Strawberry perl in a /perl/bin subdirectory on PATH.  Install perl or add to PATH and retry.  Stop.
```

Maybe related to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1023 ?

**Comment by sxa555** [comment]
Checking at https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk11_hs_extended.system_x86-64_windows/107/console ...

**Comment by sxa555** [comment]
That was it ... Couldn't remember why I'd removed it but the latest Strawberry perl SHA checksumming appears defective:

```

15:00:42  downloading dependent third party jars to C:/Users/jenkins/workspace/Test_openjdk11_hs_extended.system_x86-64_windows/openjdk-tests/\\TKG\\lib
15:00:42  downloading http://central.maven.org/maven2/org/ow2/asm/asm-all/6.0_BETA/asm-all-6.0_BETA.jar
15:00:42  ERROR: sha checksum error.
15:00:42  --> file downloaded to C:/Users/jenkins/workspace/Test_openjdk11_hs_extended.system_x86-64_windows/openjdk-tests/\\TKG\\lib\asm-all.jar
15:00:42  Expected sha is: 535f141f6c8fc65986a3469839a852a3266d1025,
15:00:42  Actual sha is  : f2f8bdd51f1a5280c7874af519fdf6425431cecd.
15:00:42  Please delete C:/Users/jenkins/workspace/Test_openjdk11_hs_extended.system_x86-64_windows/openjdk-tests/\\TKG\\lib\asm-all.jar and rerun the program!make: *** [makefile:68: getdependency] Error 255
```

**Comment by sxa555** [comment]
Retrying at https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.system_x86-64_windows/109/console with Strawberry moved explicitly after cygwin in the system `PATH`

**Comment by sxa555** [comment]
![image](https://user-images.githubusercontent.com/6487691/71676281-bdfc2d00-2d77-11ea-8962-1b70676e4f6b.png)

**Comment by sxa555** [comment]
OK ... The jenkins agent was running as a Windows service but with `Log on as: Local  System account` instead of running as the jenkins user. This seems to have the undesirable effect of the jenkins agen not running with the `PATH` from the system environment variables (for some reason that isn't clear, but is probably documented by windows somewhere). If I convert the service to run as the local `jenkins` user then it gets the desired path, and therefore works.

https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.system_x86-64_windows/111/console

Other references to this problem are at https://github.com/eclipse/openj9/issues/1736 https://github.com/AdoptOpenJDK/openjdk-tests/issues/499 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/378
