### ISSUE TITLE
Pipelines taking a long time due to significant AIX build speed degredation

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1097]
We've had to kill off a couple of AIX build jobs today due to performance issues preventing us from running the release pipelines. Builds that shoulkd take about 60-90 minutes are taking over 10 hours. This is not specific to either of the two main XLC13 build machines (The 14 and 10 hour runs shown in the screenshots below were on different machines). As can be seen from the screenshot below it's not specific to any JDK release or JVM:

![image](https://user-images.githubusercontent.com/6487691/72527363-85bd1a00-3860-11ea-8bc7-bf75fb19df67.png)
![image](https://user-images.githubusercontent.com/6487691/72527364-881f7400-3860-11ea-8655-633f5900fb42.png)

**Comment by gdams** [comment]
@sxa555 are these running on osuosl or ibm hardware?

**Comment by sej-jackson** [comment]
For the jdk8u builds, job #520 (the 10hrs one) ran on `build-osuosl-ppc64-aix-71-1` while #521 (<6hrs) ran on `build-osuosl-ppc64-aix-71-2`.

I don't see any obvious problems affecting performance on `build-osuosl-ppc64-aix-71-2`, but on `build-osuosl-ppc64-aix-71-1` its errpt showed that `rpc-lockd` was crashing at least every minute, and had been doing so since at least Monday 13th Jan (which is as far back as the logs go).  Since NFS isn't being used, I disabled the NFS-related services (`stopsrc -g nfs`) and no further entries have been logged in errpt, and the load average has dropped off (but it's also not running any jobs at the moment).  I've disabled them in `/etc/inittab`, plus also some unneeded services in `/etc/rc.tcpip` so they shouldn't restart in the event of a reboot.  This had already been done on `build-osuosl-ppc64-aix-71-2`.

I also noticed that it had only 512MB paging space (the default) which was 12% used.  Since it has 32GB RAM, I've bumped the paging to 4GB.  Again, already done on `build-osuosl-ppc64-aix-71-2`


For the jdk11u builds - both #391 & #392 were apparently run on `build-osuosl-ppc64-aix-71-2`, but I can't see any obvious performance issues on that one at the moment.

**Comment by sej-jackson** [comment]
I think last update was a bunch of red herrings though.... I'm not convinced it's showing any improvement in the current build (`#442`).

**Comment by sxa555** [comment]
Have disabled (removed build tags from) [build-osuosl-ppc64-aix-71-1](https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-1/) and [build-osuosl-ppc64-aix-71-2](https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-2/) and re-enabled [test-osuosl-ppc64-aix-71-1](https://ci.adoptopenjdk.net/computer/test-osuosl-ppc64-aix-71-1/) to allow it to run builds to compare performance

**Comment by sxa555** [comment]
I'm starting to believe this is network related (although that doesn't explain why the builds seem slow once everything is downloaded to the machine ...)

I've been doing some download tests, and it appears that HTTP downloads are havign significant problems. When trying to repeatedly download something from adoptopenjdk/github, the downloads are aborting part way through about 90% of the time:
```
-bash-5.0$ for A in `seq 1 10`; do echo $A JDK ; curl -OLJSks  https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/709/artifact/target/linux/ppc64le/openj9/OpenJDK11U-jdk_ppc64le_linux_openj9_linuxXL_11.0.6_10_openj9-0.18.0.tar.gz; echo $A TI; curl -OLJSks  https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/709/artifact/target/linux/ppc64le/openj9/OpenJDK11U-testimage_ppc64le_linux_openj9_linuxXL_11.0.6_10_openj9-0.18.0.tar.gz; done
1 JDK
1 TI
2 JDK
curl: (18) transfer closed with 179105064 bytes remaining to read
2 TI
curl: (18) transfer closed with 16802241 bytes remaining to read
3 JDK
curl: (18) transfer closed with 192987725 bytes remaining to read
3 TI
4 JDK
4 TI
curl: (18) transfer closed with 10843023 bytes remaining to read
5 JDK
curl: (18) transfer closed with 194035400 bytes remaining to read
5 TI
curl: (18) transfer closed with 17096835 bytes remaining to read
6 JDK
6 TI
7 JDK
curl: (18) transfer closed with 187225327 bytes remaining to read
7 TI
curl: (18) transfer closed with 14379211 bytes remaining to read
8 JDK
8 TI
9 JDK
curl: (18) transfer closed with 187356293 bytes remaining to read
9 TI
10 JDK
curl: (18) transfer closed with 188927514 bytes remaining to read
10 TI
curl: (18) transfer closed with 15950856 bytes remaining to read
-bash-5.0$ 
```
This is happening across both AIX and Linux machines at OSUOSL.

I have rebooted one of the systems ([build-71-2](https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-2/)) and that has not resolved the issue. I will contact OSUOSL support.

**Comment by sxa555** [comment]
Performance issues appear to have resolved themselves now

**Comment by sxa555** [comment]
Performance issues are back with a vengeance. Have had multiple buids taking over 10 hours in recent days. One of the ramdisks hit capacity, but after clearing up core dumps etc. from there the problem still persisted. Causing significant delays to pipeline execution. I am looking at [using the ramdisk for temporary files](https://github.com/AdoptOpenJDK/openjdk-build/pull/1560) as it looks like the disk I/O subsystem was  showing surprisingly high levels of utilisation

**Comment by sxa555** [comment]
This may have been successful as https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/560/ has gone through in a reasonable amount of time (~1h30 to get to the archiving artifacts stage)

**Comment by karianna** [comment]
@sxa555 safe to close?

**Comment by sxa555** [comment]
> @sxa555 safe to close?

Probably not given that I tried to do so previous, but I'll close it anyway ...
