### ISSUE TITLE
Build infrastructure for Linux x86_64 (OpenJDK + Graal builds)

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-infrastructure#1124]
On the last TSC call the vote for building graal at AdoptOpenJDK got approved. As a required step it was suggested to get dedicated builder infrastructure set up. This is the request to get this done.

For a start it should be Linux x86_64 only. CentOS 6 or 7 should work alright for this.

**Comment by sxa555** [comment]
@jerboaa I've set up [build-godaddy-rhel7-x64-1](https://ci.adoptopenjdk.net/computer/build-godaddy-rhel7-x64-1) and modified [jdk-15-gaovm-builder-x86_64_linux](https://ci.adoptopenjdk.net/job/jdk-15-gaovm-builder-x86_64_linux/) to build on `build&&rhel7&&x64&&gcc75` instead of the previous labels of `x64&&centos&&linux&&gcc75`. This will mean it runs on its own system instead of the CentOS6 machines used for our other builds. I have run it successfully on the new machine at https://ci.adoptopenjdk.net/job/jdk-15-gaovm-builder-x86_64_linux/54 - it executed in 14 minutes so consistent with the other machine, although the output it 0.5Mb smaller (may not be an issue but if you want to check that it would be appreciated)

  | Build  ↑ | Duration | Agent
-- | -- | -- | --
  | #54 | 14 min | build-godaddy-rhel7-x64-1
  | #53 | 12 min | build-digitalocean-centos69-x64-1
  | #52 | 15 min | build-softlayer-centos6-x64-1

I've also adjusted [jdk-15-gaovm-x86-64_linux](https://ci.adoptopenjdk.net/job/jdk-15-gaovm-x86-64_linux) to add `build` to the existing set of labels `x64&&rhel7`to stop it running on the test machine. I assume there was some specific reason why we had previously targetted that at `rhel7`?

That second job is currently failing, but it's failing in the same way on both machines so I'll leave the new labels in place. I'll raise a separate issue to cover the failure, and close this issue as the work to get a new system up and running is complete.

**Comment by jerboaa** [comment]
@sxa555 OK. The reason why I had the builder image job running on RHEL/CentOS 6 was done for lower glibc requirement of the resulting JDK.
