### ISSUE TITLE
Inconsistent run times of sanity.openjdk on xLinux

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1165]
While looking at the status of some of the pipelines last night it became clear that we have some quite considerable differences in the run times of some of the `sanity.openjdk` jobs. We should look at whether this is machine-specific issue and how to optimise the pipelines if there is an underlying reason.

Data from https://ci.adoptopenjdk.net/view/Build%20and%20Test%20Pipeline%20Calendar/job/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/buildTimeTrend:

  | Build  ↑ | Duration | Agent
-- | -- | -- | --
  | 153 | 9 hr 3 min |  test-godaddy-ubuntu1604-x64-1
  | 152 | 2 hr 17 min |  test-packet-ubuntu1604-x64-1
  | 151 | 4 hr 30 min |  test-scaleway-ubuntu1604-x64-1
  | 150 | 1 hr 28 min |  test-godaddy-centos7-x64-1
  | 149 | 2 hr 38 min |  test-softlayer-ubuntu1604-x64-1
  | 148 | 2 hr 4 min |  test-godaddy-ubuntu1604-x64-3
  | 147 | 9 hr 0 min |  test-godaddy-ubuntu1604-x64-1
  | 146 | 2 hr 6 min |  test-godaddy-debian8-x64-2
  | 145 | 2 hr 45 min |  test-godaddy-debian8-x64-3
  | 144 | 2 hr 24 min |  test-packet-ubuntu1604-x64-1

**Comment by Haroon-Khel** [comment]
test-godaddy-ubuntu1604-x64-1, on which the job takes 9hrs, does so because the `net`, `nio` and `rmi` tests fail. These failures usually involve test cases which return 'Connection Time out errors'. 

1 - - jdk_io_0 | 1 min 39 sec | OK | No | No
2 - - jdk_lang_0 | 14 min | OK | No | No
3 - - jdk_math_0 | 1 min 55 sec | OK | No | No
4 - - jdk_net_0 | 1 hr 40 min | NOT OK | No | No
5 - - jdk_nio_0 | 2 hr 47 min | NOT OK | No | No
6 - - jdk_security1_0 | 2 min 38 sec | OK | No | No
7 - - jdk_util_0 | 12 min | OK | No | No
8 - - jdk_rmi_0 | 3 hr 55 min | NOT OK | No | No
9 - - jdk_native_sanity_0 | 13 sec | OK | No | No

**Comment by Haroon-Khel** [comment]
Build 151, ran on test-scaleway-ubuntu1604-x64-1, was a bit odd. Only 2 tests failed, java/net/Inet6Address/B6206527.java.B6206527 and java/net/ipv6tests/B6521014.java.B6521014, which took 0.4 and 0.18 seconds respectively, yet the build took 4.5 hours

**Comment by Haroon-Khel** [comment]
The machines test-scaleway-ubuntu1604-x64-1 and test-godaddy-ubuntu1604-x64-1 seem to be the only machines which give job times outside of the average. The average range of the job time seems to be 1.5 to 2.5 hours, so anything outside of this range should be considered odd

**Comment by sxa555** [comment]
In recent runs test-godaddy-centos7-x64-1 was running the suite slower than the other machines, although test-scaleway-ubuntu1604-x64-1 has not been unduly slow (3h4m, although that run had failures) We should keep an eye in this in a weekly basis to ensure there are no significant issues

**Comment by Haroon-Khel** [comment]
Just had a quick look through the run times. All are around 1hr - 1hr 15, except for builds 277 and 275, both of which ran on test-scaleway-ubuntu1604-x64-1. These builds also had many `com/sun/jdi` test failures

**Comment by sxa** [comment]
@smlambert @adam-thorpe are you aware of those failures happening on one of our machines. While I'm somewhat tempted to just decomission this machine at some point if it's exposing a problem it would be useful to track it

**Comment by smlambert** [comment]
[search jdi in openjdk-tests repo](https://github.com/AdoptOpenJDK/openjdk-tests/issues?q=is%3Aissue+is%3Aopen+jdi) and come up with a list of issues (though mainly the jdi tests that are .sh scripts and not the tests that you link to above).  

I guess no one is triaging the sanity.openjdk suite for hotspot runs at the moment (as in trying to figure out root cause), just reporting failures in the build repo (example where some of these test failures were reported https://github.com/AdoptOpenJDK/openjdk-build/issues/1634#issuecomment-644006311).  It is somewhat telling if only failing on certain machines, that should give a triager a place to start in terms of finding root cause.

**Comment by smlambert** [comment]
Looking more closely at the jdi failures, looks to be caused by ERROR: transport error 202: bind failed: Address already in use, as in some previously started process is still using the socket, and so these tests are unable to setup and use the socket, because its already in use.  

related: https://github.com/AdoptOpenJDK/TKG/issues/45 it will be good to know what processes are still present on machines, (and if possible, what resources they still have a hold on, sockets/file handles, etc).

**Comment by sxa** [comment]
No sign of processes being left on the machine (although if they were, [sxaProcessCheck](https://ci.adoptopenjdk.net/job/SXA-processCheck/label=test-scaleway-ubuntu1604-x64-1) would have cleared it up by now) so I'm running https://ci.adoptopenjdk.net/job/Grinder/3441 and will look at the machine afterwards.

**Comment by sxa** [comment]
Seems to be running consistently in under an hour now, but I'm running https://ci.adoptopenjdk.net/view/Build%20and%20Test%20Pipeline%20Calendar/job/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/431/ on  test-godaddy-ubuntu1604-x64-1 as a final check before closing this

**Comment by sxa** [comment]
This may have been down to leftover processes on the machine. We've done a lot of work to resolve such situations recently including a run of SXA-platybookCheck with the new `kill -KILL` option which has cleared up three jobs from `extended.system` runs at the start of November (so wouldn't have been around when the initial analysis for this issue was done) but it may have been a cause.

The above job has completed in 47m minutes so the original issue is definitely resolved one way or another
