### ISSUE TITLE
Install python3 on docker build machine build-osuosl-centos74-ppc64le-1

### ISSUE THREAD

**Issue by dinogun** [AdoptOpenJDK/openjdk-infrastructure#1222]
`build-osuosl-centos74-ppc64le-1` needs python3 installed to run docker build jobs.

**Comment by sxa555** [comment]
Is this a new requirement? What has introduced it?

**Comment by dinogun** [comment]
V3 API parsing requires python3 as it does not format the output json. Please see this slack [thread](https://adoptopenjdk.slack.com/archives/CFUJV9XV0/p1580363861024500) for details.

**Comment by sxa555** [comment]
Nothing in that thread explains why it requires python3 rather than the 2.7 that's installed on that machine by default. I really don't want another large dependency on the machines unless it's strictly necessary

**Comment by dinogun** [comment]
@sxa555 I dont have a strong preference of python 3 over python 2.7, however a couple of comments

1. python3 seems to be working on all other docker build machines (x64, s390x, arm32 and aarch64)
2. Other projects (homebrew etc) seem to have a dependency on python3 as pointed out by @gdams 

It would be nice to have both the scripts and the machines to be consistent across all arches to have the same requirements.

**Comment by sxa555** [comment]
If there is no hard dependency I don't want to have different versions from the system defaults - it sounds like you can run by just referencing `python`. Another option would be to move the docker jobs onto another machine instead of using the build machines if you really need to use python3. I suspect all the other architectures that we're running on have different OSs that have it by default.

(I don't recall gdams saying python3 was needed for homebrew in the discussion I was in, only that he chose to use that as it was the default on more systems)

**Comment by karianna** [comment]
I'll add another random thought.   _if_ we can provably get Python 2x or 3 x on all of our O/S platforms then there's a case for using that as a baseline for build scripts...

**Comment by sxa555** [comment]
I'm not sure where you're going with that statement @karianna - we don't use python for out build scripts ...

**Comment by karianna** [comment]
> I'm not sure where you're going with that statement @karianna - we don't use python for out build scripts ...

Not yet we don't :-).  If we had a baseline of Python on all machines we could greatly simplify our build scripts in the long term...

**Comment by sxa555** [comment]
Closing this as we have no specific hard requirement on python3 at present

**Comment by dinogun** [comment]
The latest docker `manifest` job failed on `docker-aws-ubuntu1604-x64-1` due to lack of `python` installed. Note that I had switched over to `python` from `python3`

```
./common_functions.sh: line 551: python: command not found
```
See the full [log](https://ci.adoptopenjdk.net/job/openjdk_build_docker_manifest/label_exp=docker&&linux&&x64/100/consoleFull) for more details. Looks like `python` is not the default here

**Comment by sxa555** [comment]
Yeah I saw that -looks like Ubuntu *doesn't* set a docker->docker3 symlink when only that version is instaled which is disappointing and something I hadn't reaslied. (the change broke more than just x64) - let's put it back to be `python3` explicitly since I'm removing the docker tag from various machines that don't have `python3` installed now whic gives us more consistency in the OSs which the images are being created on, so this should no longer be a problem

**Comment by dinogun** [comment]
I think you mean python->python3 symlink. So now you want me to move to `python3` in the scripts ?

**Comment by sxa555** [comment]
Correct on both counts as I don't think there's another sensible way around this unfortunately unless we add the symlink ourselves somewhere. I genuinely hadn't realised that Ubuntu didn't set that symlink which is why I made the original recommendation to just run `python` so apologies for suggesting that change,

Out of interest - where did you make the change - I couldn't see a PR in the docker repo for changing from `docker3` to `docker`

**Comment by dinogun** [comment]
np, I'll switch over to python and for the record, didnt realize that the symlink doesn't exist either. Seems like a lot of other stuff can break as well.

**Comment by dinogun** [comment]
I made the `python3->python` change in [PR 312](https://github.com/AdoptOpenJDK/openjdk-docker/pull/312/files) as the changes that were needed, required me to add a couple of new JSON parsing code.
