### ISSUE TITLE
test-packet-ubuntu1604-x64-2 is out of disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1266]

**Comment by sxa** [comment]
There are a load of old docker images kicking around on that machine that havne't been cleaned up by the look of it (Also there's a `Sophia" directory in the workspace that's about 7Gb - @sophia-guo is that needed (Not critical that it's deleted since docker is the main issue here, and since your directory is from March it seems fairly recent)

**Comment by sxa** [comment]
Have ran the `cleanup_images` function from the machine and there is now 44G free

**Comment by sophia-guo** [comment]
@sxa  that is for test debug with same environment with jenkins builds. I have deleted it. Not realized that it's such big folder.
