### ISSUE TITLE
test-softlayer-win2012r2-x64-2: No space left on device

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1289]
See https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.openjdk_x86-64_windows_xl/61/console
```
04:28:42  tee: 'standard output': No space left on device
04:28:42  tee: 'C:/Users/jenkins/workspace/Test_openjdk14_j9_sanity.openjdk_x86-64_windows_xl/openjdk-tests/\TKG\test_output_15876221713682\TestTargetResult': No space left on device
04:33:52  make[3]: *** [autoGen.mk:30: jdk_lang_j9_0] Error 1
```

**Comment by sxa** [comment]
Hmmm the `jenkins` workspace directory has less than 20GB in it on a 100GB filesystem (7.5GB JDK14/j9/sanity-openjdk, 1.4Gb JDK11/J9/sanity-system, 8GB JDK11/J9XL/sanity-openjdk and 2Gb JDK11/J9/sanity-openjdk) so I'm not quite sure where the space is gone. I'll clear out those anyone (except the thing that's currently executing on the machine!) but we need to look into the 80GB that's being chewed up elsewhere as that seems very high.

**Comment by sxa** [comment]
Executive summary:
`cygwin64` 11Gb
`pagefile.sys` 2.5Gb
`Program Files` 4Gb
`Program Files (x86)` 27Gb
`ProgramData` 8Gb
`temp` 1.2Gb (Mostly the 200Mb `jdk-xx.zip` files
`Users` 2Gb (includes jenkins workspace)
`Windows` 20Gb
so that is over 70Gb. Generally the test jobs don't require too much and are good at cleaning up after themselves, so while it's a little tighter on space than I'd like I'm ok to close this now we've cleared 20gb of space

**Comment by Willsparker** [comment]
I know this is closed - could we not remove the `jdk-xx.zip` files , as unzipped versions should all be in `C:/openjdk/` ?
Better yet, could we remove them at the end of the `Java_install` role?

**Comment by sxa** [comment]
Yes to all of the above @Willsparker
