### ISSUE TITLE
Test Windows builds with Freetype 2.10.2

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1337]
Ref https://github.com/AdoptOpenJDK/openjdk-build/pull/1757

We are currently using Freetype 2.5.3 (JDK8) and 2.9.1 (JDK11+) to build windows. Freetype 2.10.2 has been released however, so it should be worth investigating whether we can build with the upgraded version.

I propose the following tests for a single nightly run (see [windows.sh](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh) for making these changes):
- Run a JDK8 nightly with `--freetype-version 2.10.2`
- Run a JDK11 nightly with `--freetype-version 2.10.2`

**Comment by M-Davies** [comment]
@Willsparker Do you have the perms to run these sort of tests?

**Comment by sxa** [comment]
(Did you mean this to be in openjdk-infrastructure instead of openjdk-build?)

Assuming they will both auto-download a new version here are runs against your PR branch:
[JDK8](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/611/OS=Win2012,label=infra-softlayer-ubuntu1804-x64-1/parameters/)
[JDK11](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/612/OS=Win2012,label=infra-softlayer-ubuntu1804-x64-1/parameters/)
(It's possible that these will fail for reasons unrelated to your change, but it's worth a shot. Will is off today)

**Comment by M-Davies** [comment]
Yes I did. Ref @karianna 's comment in https://github.com/AdoptOpenJDK/openjdk-build/pull/1757#pullrequestreview-416192782. The idea being we run one off builds with Freetype 2.10.2 and see what happens. Looks like the two builds above failed for connection reasons unrelated to this

**Comment by Willsparker** [comment]
@M-Davies 
I've had a go on an already setup VM on my Mac. Building JDK8/OpenJ9 (or more specifically, building `Freetype 2.10.2` was unfortunately unsuccessful with the error being: 
![Screenshot 2020-05-26 at 09 14 45](https://user-images.githubusercontent.com/52783864/82876904-641c1f80-9f31-11ea-90dc-f85a1ebd4e3d.png)
However, building JDK11/OpenJ9 didn't come up with the same error - it was saying that my MSVS_2017 compiler couldn't create executables ( This may be due to some issues with my VM however, therefore confirming with a [VPC run](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=Win2012,label=infra-softlayer-ubuntu1804-x64-1/614/console) )

From what I can gather, the new version of Freetype needs to have a later-than-2010 version of MSVS  to build it, however, it sets the C compiler to whatever the build uses (I.e. MSVS_2010 for JDK8/J9 , MSVS_2017 for JDK11+/J9 etc).

**Comment by karianna** [comment]
OK so we're still gated by the build issue to get all Java 8 builds onto VS code 2017

**Comment by Willsparker** [comment]
Assuming we can't do something like pre-build freetype with MSVS_2017 and then bundle it into a JDK8 built with MSVS_2010, yes.
We could certainly put _some_ of the freetype versions up to `2.10.2` - Anything with `TOOLCHAIN_VERSION="2017"` in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh
Are they required to all be the same version? If not, we could just do that for JDK11+

**Comment by karianna** [comment]
> Assuming we can't do something like pre-build freetype with MSVS_2017 and then bundle it into a JDK8 built with MSVS_2010, yes.
> We could certainly put _some_ of the freetype versions up to `2.10.2` - Anything with `TOOLCHAIN_VERSION="2017"` in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh
> Are they required to all be the same version? If not, we could just do that for JDK11+

I think we need to complete the work to build Java 8 on the VSCode 2017 toolchain

**Comment by M-Davies** [comment]
@karianna Where is the issue for that?

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/issues/466

**Comment by Willsparker** [comment]
If nobody minds, I'm going to close the issue as the testing has been done and we're currently blocked by moving Java8 over to using VS2017 :-)
