### ISSUE TITLE
Reinstate test-softlayer-win2012r2-x64-1 in jenkins

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1343]
I guess this was removed as it wasn't in jenkins. We should probably see if we can get into it and run some tests on it to increase our testing capacity (maybe after searching issues to see if there was a reason it was shut down and/or repurposed)

_Originally posted by @sxa in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1342#issuecomment-635336985_

**Comment by Willsparker** [comment]
So.... This machine hasn't had the playbook ran on it. Interesting ...

**Comment by Willsparker** [comment]
Running the playbook on it, it failed halfway through the `Cygwin` role. When trying to restart the ansible connection, either through `ansible all` or `ansible-playbook`, I was met with the following error message: 
```
localhost:ansible williamparker$ ansible all -i playbooks/AdoptOpenJDK_Windows_Playbook/hosts -u Administrator -m win_ping

[DEPRECATION WARNING]: DEFAULT_SQUASH_ACTIONS option, Loop squashing is deprecated and this configuration will no 
longer be used , use a list directly with the module argument instead. This feature will be removed in version 2.11. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

[WARNING]: ERROR DURING WINRM SEND INPUT - attempting to recover: WinRMError The pipe has been ended.  (extended fault
data: {'transport_message': 'Bad HTTP response returned from server. Code 500', 'http_status_code': 500,
'wsmanfault_code': '109', 'fault_code': 's:Receiver', 'fault_subcode': 'w:InternalError'})
169.55.170.72 | FAILED! => {
    "msg": "winrm send_input failed; \nstdout: \nstderr PowerShell : The term 'PowerShell' is not recognized as the name of a cmdlet, \r\nfunction, script file, or operable program. Check the spelling of the name, or \r\nif a path was included, verify that the path is correct and try again.\r\nAt line:1 char:1\r\n+ PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted - ...\r\n+ ~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (PowerShell:String) [], CommandN \r\n   otFoundException\r\n    + FullyQualifiedErrorId : CommandNotFoundException\r\n "
}
```
This was due to (I believe) part of the Cygwin role changing the Windows Path, adding a speech mark to the end of the `path` environment variable. This caused the last item at the end of the path, which happened to be the path the `C:/Windows/System32/WindowsPowerShell/v1.0` to become invalid and therefore Ansible couldn't find `powershell`. Removing the added speech mark reinstated `powershell` into the path and allowed ansible to connect.

**Comment by Willsparker** [comment]
To do:

- [ ] Connect to machine
- [ ] Run playbook on machine
- [ ] Create node in Jenkins
- [ ] Connect node to Jenkins
- [ ] Run test Grinders

**Comment by Willsparker** [comment]
Note: The machine has an unallocated 25GB virtual disk. The `C:/` drive is at 100GB max capacity, with 22.1GB free after the playbook has ran through.

**Comment by Willsparker** [comment]
Running sanity.openjdk Grinder on it: https://ci.adoptopenjdk.net/job/Grinder/3249/console

**Comment by Willsparker** [comment]
Grinder ran through okay, closing the issue
