### ISSUE TITLE
jdk8 Solaris : curl: (60) SSL certificate problem: certificate is not yet valid

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1346]
**Platform:**
Solaris
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/321/console
```
18:07:31  curl: (60) SSL certificate problem: certificate is not yet valid
```

**Comment by sxa** [comment]
Failing URL is https://ftp.osuosl.org/pub/blfs/conglomeration/alsa-lib/alsa-lib-1.1.6.tar.bz2

**Comment by sxa** [comment]
[build-siteox-solaris10u9-x64-1](https://ci.adoptopenjdk.net/computer/build-siteox-solaris10u9-x64-1) has now caught up with the start date of this certificate so this is no longer blocking builds, however the builds are broken in other ways now.

I'll leave the open until the time on the server is fixed since I assume it's still behind ...

**Comment by sxa** [comment]
Being addressed under a recurrance at https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1430
