### ISSUE TITLE
test-softlayer-win2012r2-x64-1   I/O problems

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1404]
**Test_openjdk14_j9_sanity.openjdk_x86-64_windows:**
https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.openjdk_x86-64_windows/112/console
```
ERROR: Failed to clean the workspace
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk14_j9_sanity.openjdk_x86-64_windows\openjdk-tests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

**Comment by karianna** [comment]
@Willsparker - I wonder if we're seeing a cygwin bug here as well.  How old are the Cygwins on those machines?

**Comment by Willsparker** [comment]
ref: #1396 

@karianna I think it's due to leftover processes. When I try and delete it using file explorer (as Admin), I get this:
<img width="458" alt="Screenshot 2020-06-22 at 13 46 18" src="https://user-images.githubusercontent.com/52783864/85289084-c7e12c00-b48e-11ea-93f4-fd7b820a602b.png">

When I go through resource monitor, I can see there's still some java processes running on it:
<img width="649" alt="Screenshot 2020-06-22 at 13 48 54" src="https://user-images.githubusercontent.com/52783864/85289312-26a6a580-b48f-11ea-890f-14558cbc7bf8.png">

Once I end the Java processes manually, I'm able to delete the file.

The version this machine is running (according to `uname -r` in the Cygwin terminal) is `3.1.5(0.340/5/3)`, which I believe is the latest version of cygwin (https://www.cygwin.com/)

**Comment by Willsparker** [comment]
I suppose it could be a Cygwin issue, however, Jenkins is meant to have a way of auto killing any process that is spawned within a job (see https://wiki.jenkins.io/display/JENKINS/ProcessTreeKiller ), so unless Cygwin escapes that somehow, this shouldn't happen.. :/

**Comment by Willsparker** [comment]
I'm going to close this issue as the workspace has been cleared now - We have #1396 to track how to possibly fix it :-)
