### ISSUE TITLE
Timeout running ansible playbook on Windows

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1436]
I used the ansible playbook to setup a Windows 2012 Server machine for building the openj9 jdk following these instructions: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/README.md.
The playbook failed during the cygwin install step (and after multiple attempts) with messages (on the linux machine running ansible) like:
```
TASK [cygwin : Install Cygwin and its packages] ********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ConnectTimeout: HTTPSConnectionPool(host='x.xx.xxx.xxx', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1f31ef2d10>, 'Connection to x.xx.xxx.xxx timed out. (connect timeout=30)'))
fatal: [x.xx.xxx.xxx]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
(The x.xx.xxx.xxx was the IP address of the Windows machine on which cygwin was being installed.)

I found setting these additional ansible parameters fixed the timeout:
```
ansible_winrm_operation_timeout_sec: 600
ansible_winrm_read_timeout_sec: 630
```
Perhaps https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/README.md should be updated to either say 'set these parameters' or to have a 'Troubleshooting' section?  Or maybe the existence of this issue will suffice?

**Comment by sxa** [comment]
Interesting - assuming that's 600 as in 600 seconds (10 minutes) that seems to be less than the amount of time it took in e.g. https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/668/console (22 minutes) which didn't time out.

@Willsparker Have you done anything in VPC to adjust these timeouts from the defaults?

I agree that this should be documented somewhere other than this issue because that step does take quite a while.

Related: If we could cache it appropriately that would likely help with this https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1210

**Comment by lumpfish** [comment]
I don't know what ansible defines as an 'operation' - but the cygwin install actually took way longer that the 600 sec timeout might imply would trigger the timeout (but which nevertheless worked for me).  There may well be something more subtle going on.

**Comment by Willsparker** [comment]
The only timeout I change in `VPC` is in the `ansible.cfg` and only applies to the Linux machines. (https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/c9902f959118f2f66d3470a31a7809213c904b6f/ansible/pbTestScripts/vagrantPlaybookCheck.sh#L227 )
I haven't had the Cygwin installation timeout for me like that, unless I had locked my mac for whatever reason, whilst the playbook was executing. Running the playbook in a `screen` session would fix this.
 
I'm happy to put this in the README.md though, until we can figure out how to cache the `Cygwin` installation and timeout isn't likely.

**Comment by sxa** [comment]
Is that in minutes? i.e. is that setting it to 30 minutes which would be higher than the amount of time that the cygwin install takes?

**Comment by Willsparker** [comment]
It's in seconds, but as I said, it isn't changed in a Windows run of `VPC`. 
https://docs.ansible.com/ansible/2.4/ansible-playbook.html#cmdoption-ansible-playbook-t
That particular line is just overriding the default connection timeout time of 10s to 30s.
IIRC I put that in when I changed the playbook to run on a host and point at a VM instead of on the VM itself, and the addition of the `--become` [option](https://docs.ansible.com/ansible/2.4/ansible-playbook.html#cmdoption-ansible-playbook-b) to the ansible-playbook command and for some reason intermittently needed a longer timeout.

This doesn't affect how long a given task can take, but how long ansible can take to connect to the ssh server of the VM. https://stackoverflow.com/a/54760097

**Comment by sxa** [comment]
@Willsparker Is there a good reason not to make those increased values the defaults?

**Comment by Willsparker** [comment]
I suppose we could just add those variables to `/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml`, however, this has only occurred once, as far as I'm aware. Increasing the timeout ~20x by default seems a bit overkill

**Comment by sxa** [comment]
Hmmm ok if @lumpfish really only hit it once and it doesn't recur then I'm ok with that.
