### ISSUE TITLE
build-osuosl-aix71-ppc64-1 ulimit concern

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1443]
Test Zip64SizeTest fails on this machine with an error referencing ulimit sizes:
```
[2020-07-12T02:10:39.865Z] java.io.IOException: A file cannot be larger than the value set by ulimit.
```

Examples here:
https://trss.adoptopenjdk.net/output/test?id=5f0a74bf7eaab3443c9c4062
https://trss.adoptopenjdk.net/output/test?id=5f0b99257eaab3443c9dc1a0

**Please review the ulimit settings on this machine and correct if needed.**

Note that we had the same test+machine combo pass on the 9th at 2:29am, so I presume something changed since this ran:

https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_ppc64_aix/144/

**Comment by sxa** [comment]
@adamfarley Can you run a couple of grinders to verify whether that test in isolation fails with the latest build and the one from the 9th?

**Comment by sxa** [comment]
I've been able to create a file of over 5GB on the /home filesystem. The ramdisk where the workspace is seems to hit a limit at 2Gb although that's not a ulimit issue:

```
Result: time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     unlimited
nofiles(descriptors) unlimited
threads(per process) unlimited
processes(per user)  unlimited
```

**Comment by adamfarley** [comment]
Here's a 10x grinder for this test in isolation using the java from the run on the 9th (the one that passed).

https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_ppc64_aix/149/console

And here's one for the latest build:

https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_ppc64_aix/150/

(Despite the fact it says it's being run by George Adams)

**Comment by adamfarley** [comment]
The test run against the build from the 9th didn't happen, as that build wasn't found.

From the looks of things, that build has already been deleted.

**Comment by sxa** [comment]
The builds are all stored in github and are accessible via the [nightlies pages](https://adoptopenjdk.net/nightly.html) (which is why we don't generally need to keep more than a couple to make sure they're accessible to subsequent pipelines in a build)

In this case the difference is nothing to do with ulimits (you can see in the logs that it prints out a ulimit and it's unlimited for file size) however on machines which are using a ramdisk which is formatted as jfs rather than jfs2 there is an inherent 2Gb limit in the file system itself. We've already been looking at making some changes in that area while will probably resolve this but I'm holding off on system changes at the moment during the GA cycle.

Somewhat surprised that I don't recall seeing this being reported before!

**Comment by adamfarley** [comment]
Me too. I don't suppose this disk was reformatted on the 9th or later?

In any case, assuming the 2gb file size limit is the cause, this test will be excluded on ppc64le until this issue is resolved.

https://github.com/AdoptOpenJDK/openjdk-tests/pull/1896

**Comment by sxa** [comment]
@adamfarley This is AIX not Linux/ppc64le

**Comment by sxa** [comment]
Passed at https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_ppc64_aix/160/

**Comment by sxa** [comment]
Exclusion reverted under https://github.com/AdoptOpenJDK/openjdk-tests/pull/1902

**Comment by adamfarley** [comment]
Thanks Stewart.
