### ISSUE TITLE
Determine differences between the 2 linux_x86-64 test machines

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#145]
Need to resolve configuration differences between the 2 linux_x86-64 machines:

test-scaleway-x64-ubuntu-16.04-1 
and
test-packet-x64-ubuntu-16.04-1   

Docker-based tests pass on the scaleway machine, and fail on the packet machine.  

Failure message: 
18:23:57      [exec] Status: Image is up to date for adoptopenjdk/openjdk8:latest
18:23:57      [exec]  ---> 8ede58073db6
18:23:57      [exec] Step 4/12 : RUN apt-get update 	&& apt-get -y install 	ant 	apt-transport-https 	ca-certificates 	dirmngr 	curl 	git 	make 	unzip 	vim 	wget
18:23:57      [exec]  ---> Running in 556463860d06
18:23:57      [exec] [91mcontainer_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\""
18:23:57      [exec] oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\""

I checked that they both have the same version of Docker installed (Docker version 17.09.1-ce, build 19e2cf6).

**Comment by bletherhead** [comment]
Apparently the error `fork/exec /usr/bin/dockerd (deleted): no such file or directory` can be caused by something deleting and recreating `/usr/bin/dockerd` whilst it's still running, so that the inode of `/usr/bin/dockerd` doesn't match the inode of the existing dockerd process.  
Looking on test-packet-x64-ubuntu-16.04-1 I can see that dockerd was started on October 18th last year, and the docker-ce package was updated on December 11th.  
I've restarted the Docker service. Does that fix the issue?

**Comment by gdams** [comment]
ping @smlambert

**Comment by smlambert** [comment]
Saw this, tried rerunning yesterday but Jenkins reboot blocked launching new builds... will rerun now.

**Comment by smlambert** [comment]
Thanks, they are now running on both machines.

**Comment by smlambert** [comment]
BTW, does it imply that after an ansible refresh an additional step should occur (restarting services)?

**Comment by bblondin** [comment]
not a bad idea... it is currently set to ```started```, I will update it to ```restarted```
This will ensure the service gets bounced.
