### ISSUE TITLE
Nodes are running out of disk space too frequently

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1591]
It seems every week we get half a dozen or so builds hang due to low disk space. Can we increase the node monitoring script(?) to alert if a node is below a higher figure? Say 50Gb?
Does the monitoring take a node offline if below the threshold? so that it does not cause a hung build...

**Comment by Willsparker** [comment]
I agree- I think the nodes filling up with space is definitely an issue. I think the problem with a blanket monitoring script though, is that often machines have different levels of what's full or not - i.e. Some test windows machines have only 100GB on C:\ drive , so 5GB free on it is pretty good. Whereas some build machines, 5GB is barely anything.

**Comment by aahlenst** [comment]
@andrew-m-leonard Documenting what's required and identifying the machines that need more disk space might be a good idea and a fitting extension of your project to catalogue our machine park. If we can figure out a percentage of required free space, we could feed that into our monitoring software.

**Comment by andrew-m-leonard** [comment]
@aahlenst @sxa has some info on the machine resource already, but needs more discussion.

**Comment by sxa** [comment]
We need to be clear on what the requirement on each build machine is and what the size of the builds are on each individual platform. Also bear in mind it's going to change over time. The OpenJ9 builds weren't 10Gb each a couple of years ago :-)

If they are running out regularly because the working set is simply too large for the amount of space we allocated on the machines, then we need to start looking at expanding them where appropriate. And as mentioned above some machines have low amounts of space allocated to them (Scaleway machines are 50Gb for the arm32 ones as I recall, but they don't build OpenJ9 so the requirements are lower).

@andrew-m-leonard Can you log in here the systems you've been seeing issues on please so we can understand if we should do something on those in particular, and to validate whether it is due to increased size of the total build sizes and not something else?

**Comment by andrew-m-leonard** [comment]
5th Oct: 
build-osuosl-aix71-ppc64-2 : Raised: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1589
test-softlayer-win2012r2-x64-2 : Raised: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1590

**Comment by karianna** [comment]
I've bumped the Jenkins notifier to warn on <10GB

**Comment by sxa** [comment]
Agree with @aahlenst - we need to be able to document what we need and then ensure the infrastructure is adequate for purpose. Over time with new releases (always larger than the previous ones) our usage expands and so we hit these issues and will continue to do so unless some extra planning is done at the time of new releases coming out.

The first step is definitely to understand what we NEED.

**Comment by sxa** [comment]
@andrew-m-leonard Do we have a list of the "half a dozen or so per week"?

**Comment by sxa** [comment]
> I've bumped the Jenkins notifier to warn on <10GB

@karianna I think this has knocked quite a few nodes offline which are still capable of operating effectively so this change is going to break things overnight if we leave it in place, so I would suggest taking it a bit lower for now to avoid introducing extra problems, then work towards increasing it to 10GB. A couple of the AIX amd arm32 ones we have are using a 30GB workspace FS just now, but it's adequate for the jobs being run on there at the moment.

**Comment by karianna** [comment]
@sxa - replied on Slack - LMK if you want me to drop to say 5GB

**Comment by sxa** [comment]
Am ok for now - let's leave it and see if it causes any other problems. It might do for some of the smaller systems but I think we're ok with the pipelines at least for today ;-)

**Comment by sxa** [comment]
Am ok for now - let's leave it and see if it causes any other problems. It might do for some of the smaller systems but I think we're ok with the pipelines at least for today ;-)

**Comment by sxa** [comment]
It doesn't seem that we have any important machiens that are having problems with this new policy, so I'm closing as complete and we can resolve individual instances as they show up.
