### ISSUE TITLE
Replace "softlayer" machines with "ibmcloud" ones

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1594]
The IBM owner of the account that manages our machines in IBM's cloud is changing and as part of these we're rebuilding all of the machines. To begin with we have recreated them with the provider name of "ibmcloud" instead of "softlayer" and will start activating the new ones in jenkins this week with a view to deactivating the old ones shortly afterwards once the new ones are validated as working.

The full list of new systems is as follows (names here shortened from what they will be in jenkins purely because of a hostname limit)

As each of these is activated I'll link to the new definitition in jenkins:

- [x] infra-ibmcloud-vagrant-x64 = 169.48.4.135
- [x] [test-ibmcloud-rhel6-x64-1](https://ci.adoptopenjdk.net/computer/test-ibmcloud-rhel6-x64-1/) = 169.48.4.140
- [x] [test-ibmcloud-rhel7-x64-1](https://ci.adoptopenjdk.net/computer/test-ibmcloud-rhel7-x64-1/) = 169.48.4.136
- [x] [test-ibmcloud-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-ibmcloud-ubuntu1604-x64-1/) = 169.48.4.141
- [x] bld-ibm-w2012x1 ([build-ibmcloud-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/build-ibmcloud-win2012r2-x64-1/)) = 169.48.4.138
- [x] bld-ibm-w2012x2 ([build-ibmcloud-win2012r2-x64-2](https://ci.adoptopenjdk.net/computer/build-ibmcloud-win2012r2-x64-2/)) = 169.48.4.142
- [x] tst-ibm-w2012x1 ([test-ibmcloud-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/test-ibmcloud-win2012r2-x64-1/)) = 169.48.4.131
- [x] tst-ibm-w2012x2 ([test-ibmcloud-win2012r2-x64-2](https://ci.adoptopenjdk.net/computer/test-ibmcloud-win2012r2-x64-2/)) = 169.48.4.139

**Comment by Willsparker** [comment]
`test-ibmcloud-win2012r2-x64-*` and `build-ibmcloud-win2012r2-x64-*` have had their playbooks run but are yet to have tests / builds ran on them. 
`infra-ibmcloud-vagrant-x64` has had the `vagrant.yml` playbook ran on it- however the QEMU disk images needs to be transferred over to them. Testing for this needs to be done too (though I'll probably define it in Jenkins first and then use `vagrantPlaybookCheck` to test it)

**Comment by sxa** [comment]
That's ok - I haven't installed the agent service on the machines yet so they're not "live" in jenkins. Feel free to do the appropriate testing and enable the service at your convenience  @Willsparker :-)

**Comment by Willsparker** [comment]
Current issue affecting the Windows boxes, It seems `shortnames` are enabled, and most directories have one, but 'Program Files (x86)' don't. Looking into manually assigning them now :+1:

**Comment by sxa** [comment]
I thought we had that covered in the playbooks now?

**Comment by Willsparker** [comment]
We do - shortnames are enabled, and a lot of shortnames are there, it just decided not to assign one to `Program Files (x86)` for some reason. Difference in machines from different providers, I would assume, but I'll look at adding that to the playbooks :-)

**Comment by Willsparker** [comment]
https://superuser.com/questions/681330/how-to-force-short-name-8dot3-generation
Unfortunately, it looks like we need to create the short-name in `safe mode`, as attempting to create the shortnames when the machine isn't running in safe mode will give an `Access is denied` error message (due to the files being in use).

**Comment by Willsparker** [comment]
@sxa found that if the `incredibuild` tasks were ended, it's possible to create a shortname for `Program Files (x86)`. I confirmed that worked on both of the new build machines. Test builds of JDK15/J9 are running on them now :-)

**Comment by Willsparker** [comment]
The windows machines are going to have to be re-provisioned unfortunately, due to not having enough disk space on them (I believe they're all 100Gb, which is only just enough to run the full playbook on them).

**Comment by Willsparker** [comment]
Quote from @sxa in private channel:
"_The infra team in Hursley has said that they can add another disk to the windows machines so we can use that for the jenkins workspace dir once it's been added, leaving the existing 100Gb boot disk as-is, so shouldn't need a reinstall._"

Due to this, I'm replacing the cached Cygwin install with the new lightweight install, on all machines. I've added OpenSSL 1.1.1h on the build machines (as the initial playbook run was before #1597 was merged). Testing will then be done on all machines:

Cygwin re-install:
- [X] bld-ibmcloud-win-x64-1
- [ ] bld-ibmcloud-win-x64-2
- [X] tst-ibmcloud-win-x64-1
- [ ] tst-ibmcloud-winx64-2

Build / Test carried out: 
- [ ] bld-ibmcloud-win-x64-1
- [ ] bld-ibmcloud-win-x64-2
- [ ] tst-ibmcloud-win-x64-1
- [ ] tst-ibmcloud-winx64-2

**Comment by Willsparker** [comment]
@sxa Do you know how much extra disk space the windows machines are getting and when it will be added?

**Comment by sxa** [comment]
It is awaiting approval from IBM so I cannot provide an ETA yet but it will be at least double what's there and ideally 500GB+

**Comment by Willsparker** [comment]
ref: #1632 
Can this issue be closed now?

**Comment by sxa** [comment]
The last potential issue has been confirmed as a one-off non-issue with one of the systems
@tellison has now decomissioned them
