### ISSUE TITLE
Windows sign_build cannot run on build-ibmcloud-win2012r2-x64-1

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1615]
Signing job does not seem to work on build-ibmcloud-win2012r2-x64-1

https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/12034/console

**Comment by andrew-m-leonard** [comment]
Sign job works fine on build-azure-* and build-softlayer-*

**Comment by Willsparker** [comment]
I'll remove the tags - the new IBMCloud window machines still need to have disk space added, so they'll remain offline for the minute anyway.
The actual error message(s):
```
[WS-CLEANUP] Deferred wipeout is used...
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 8a.04.30a9.ip4.static.sl-reverse.com/169.48.4.138:51616
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
...

java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
...
```
Looks to be a permissions issue, along with possibly an unstable Jenkins agent.

**Comment by Willsparker** [comment]
(Both machines had the `Wix` tag removed)

**Comment by Willsparker** [comment]
Alright, I've had a look at the machines and compared them to the Azure machines.
The group `AdoptOpenJDK Jenkins User` needs `full control` to wherever on the machine is identified as the Jenkins workspace. i.e. `C:/users/jenkins` for the Softlayer machines, `J:/jenkins` for the Azure machines.
For now, as we still need to add the extra space to the build machines, that workspace isn't really defined, (however, I assume it's going to be similar to the Azure machines). Due to this, I can't fix the permissions until the disks have been added, so in the meantime, I'm going to mark the machines as temporarily offline.

**Comment by karianna** [comment]
I've added https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1617 JIC we accept George's PR

**Comment by sxa** [comment]
Jenkins user on the machine did not have permission to write to the directory which was defined as it's `Remote Root directory` on the jenkins agent definition, therefore no jobs could run on it (i.e. this issue is unrelated to the signing job specifically)

**Comment by Willsparker** [comment]
Both machines have had `C:/users/jenkins` perms updated so the Jenkins user has `Full Control`. Closing issue
