### ISSUE TITLE
Several Dockerfilecheck jobs are not completing successfully

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1725]
https://ci.adoptopenjdk.net/job/DockerfileCheck

FYA @Willsparker

**Comment by Willsparker** [comment]
Ah, I know what the issue is ... 
Before the build-scripts get to making the docker container, they try to find the JDK-BOOT-DIR on the host machine. Being that they're docker machines, they only have JDK8 installed (hence why JDK8 works). So the build scripts fail before even building the container. (https://github.com/AdoptOpenJDK/openjdk-build/issues/1707)

The issue started here: https://github.com/AdoptOpenJDK/openjdk-build/pull/2119
