### ISSUE TITLE
Ansible request for build-godaddy-win2016-x64-1 OpenSSL-1.1.1h-x86_64-VS2017 missing

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1728]
```
08:31:17  checking for OPENSSL... configure: The path of OPENSSL_DIR, which resolves as "/cygdrive/c/openjdk/OpenSSL-1.1.1h-x86_64-VS2017", is invalid.
08:31:17  configure: error: Cannot locate the the path of OPENSSL_DIR
```
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/205/console

**Comment by sxa** [comment]
I'm somewhat surprised this hasn't shown up before. Has this machine bene recently enabled or have we just been lucky enough never to hit it with an OpenJ9 build? This machine is also Windows 2016 instead of 2012r2 like the other ones ...

FYI @Willsparker as this possibly got missed in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1578

**Comment by sxa** [comment]
I've marked the machine offline until it can be made operational again

**Comment by Willsparker** [comment]
Ah - that was a machine that @gdams asked me to setup late last week, but we've got an issue where downloads (either through CLI or via a browser) are at a rate of about 15KB/s. I hadn't connected it to Jenkins, and I certainly didn't add the labels to it. The issue was downloading the Strawberry Perl zip, hence I wasn't able to build the OpenSSL versions on them.

**Comment by Willsparker** [comment]
It appears to be *just* the Strawberry Perl URL that we download from. For some reason on my laptop it's faster at a couple hundred kB/s (which is still fairly slow), so I've just used `win_copy` to copy it over. I'll post here when the OpenSSL versions have been put on there.

**Comment by Willsparker** [comment]
All OpenSSL versions have been installed, (and the playbook finished running) :-) Closing issue

**Comment by sxa** [comment]
> Ah - that was a machine that @gdams asked me to setup late last week

Where is that work being tracked?
