### ISSUE TITLE
Request for Windows Folders to have Short Names set

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1731]
As a follow-on to issue #1729, this is a request to have short names set for the following folders across all Windows x64 build machines:

- C:/Program Files
- C:/Program Files/NVIDIA GPU Computing Toolkit

This can be achieved via direct modification, or a full reinstall.

This change will allow us to enable cuda support in the builds we create, as we need paths with no spaces (thus the use of the short folder names).

Related to https://github.com/AdoptOpenJDK/openjdk-build/issues/2272

**Comment by Willsparker** [comment]
Explanation why this _probably_ isn't doable in the playbook: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1729#issuecomment-737778586

I had a test on a windows machine that already had the shortnames enabled, and Program Files already had one . Just setting the shortname didn't work with an `Access Denied` error message, which is due to processes running in `Program Files`. This is a machine that's only had the Jenkins role run on it, so it's nothing we installed. IIRC, it was a `amazon-agent` process and a `microsoft SQL server` process. Having stopped those, I tried again and it gave me a different error saying something to effect of `Can't assign a shortname to a directory that already has one`, which leads me to believe that if I tried this on a system that doesn't have a shortname for `Program Files`, it would work. 

 So, list of machines to fix the shortnames of:

- [ ] build-azure-win2012r2-x64-1
- [ ] build-azure-win2012r2-x64-2
- [ ] build-ibmcloud-win2012r2-x64-1
- [ ] build-ibmcloud-win2012r2-x64-2

**Comment by adamfarley** [comment]
Good job Will. :)

Yes, many machines have one of those two folders equipped with a short name, but I couldn't find one with both folders having a short name. Only one lacks the Program Files short name, but it's best to check them all.

Note: We need *both* the Program Files *and* NVIDIA GPU Computing Toolkit to have short names.

**Comment by Willsparker** [comment]
Yep, `build-azure-win2012r2-x64-*` has `Program Files`, it's the IBMCloud machines that don't :-) `azure` ones are good

**Comment by Willsparker** [comment]
And `build-ibmcloud-win2012r2-x64-*` have been done; closing issue :+1:

**Comment by adamfarley** [comment]
Thanks @Willsparker
