### ISSUE TITLE
jdk15 does not run on test-ibmcloud-rhel6-x64-1

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1746]
When jdk15 tests land on test-ibmcloud-rhel6-x64-1 java -version fails with the message:
```
13:13:27  Run /home/jenkins/workspace/Test_openjdk15_j9_sanity.functional_x86-64_linux_xl/openjdkbinary/j2sdk-image/bin/java -version
13:13:27  =JAVA VERSION OUTPUT BEGIN=
13:13:27  /home/jenkins/workspace/Test_openjdk15_j9_sanity.functional_x86-64_linux_xl/openjdkbinary/j2sdk-image/bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/jenkins/workspace/Test_openjdk15_j9_sanity.functional_x86-64_linux_xl/openjdkbinary/j2sdk-image/bin/../lib/libjli.so)
```
Sample run: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.functional_x86-64_linux_xl/29/console

**Comment by sxa** [comment]
This is OpenJ9 specific. We switched some of the builds [back to building on CentOS6](https://github.com/AdoptOpenJDK/openjdk-build/pull/2154/files ) due to an end-user concern. The statement from OpenJ9 is clear that [they do not support running on that level](https://github.com/AdoptOpenJDK/openjdk-build/pull/2154#issuecomment-712977169)

The question therefore becomes whether we should stop testing on it completely, or find a way to stop the OpenJ9 JDK15+ builds from being scheduled on this system. (FYA @smlambert)

**Comment by lumpfish** [comment]
One way would presumably be to make jdk release be one of the Jenkins machine label attributes.  Bit of a maintenance issue each time a new release comes along though.

**Comment by sxa** [comment]
> One way would presumably be to make jdk release be one of the Jenkins machine label attributes. Bit of a maintenance issue each time a new release comes along though.

Yep ... it'll be a pain ;-)

**Comment by lumpfish** [comment]
Just hit this again testing the openj9-0.24.0-m2 jdk15 builds.  It would be good not to risk landing on this machine when we do the Jan 2021 release builds.

**Comment by andrew-m-leonard** [comment]
and again: https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk15_j9_extended.system_x86-64_linux_xl/147/

**Comment by sxa** [comment]
Should be fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2372 which has now been merged
