### ISSUE TITLE
Add cvs install to ancible scripts to enable openjdk-systemtest test execution

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#18]
The tests run part of the mauve test suite as a load test, and need to checkout the mauve test suite which is in a cvs repo.

**Comment by sxa555** [comment]
It may be possible to get around this requirement by using the java CVS client which was developed for NetBeans and is available from https://netbeans.org/projects/versioncontrol/downloads/ (Second link on there is to the jar file) - As long as we have no licensing concerns then that could be downloaded on the fly and used in place of the "real" cvs client. I've trialled this using a little shell script wrapper called "cvs" to invoke it and it seems to work.

We could modify the ant tasks to download and use this version (since we will always have a JRE of some sort available) which would eliminate cvs as a prereq on the machine

**Comment by tellison** [comment]
I'm assuming you want this on all suitable machines.
For now I have manually added CVS to `build-osuosl-ppc64le-centos-7.2` (only on the grounds that it is the same machine where @sxa555 needed git ).

Once I get clarity on the Ansible scene I'll update everywhere.

```
$ cvs --version

Concurrent Versions System (CVS) 1.11.23 (client/server)

Copyright (C) 2006 Free Software Foundation, Inc.

Senior active maintainers include Larry Jones, Derek R. Price,
and Mark D. Baushke.  Please see the AUTHORS and README files from the CVS
distribution kit for a complete list of contributors and copyrights.

CVS may be copied only under the terms of the GNU General Public License,
a copy of which can be found with the CVS distribution kit.

Specify the --help option for further information about CVS
```

**Comment by sxa555** [comment]
Now no longer needed as https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/4 has been merged so we're using a dynamically downloaded java cvs client
