### ISSUE TITLE
build-osuosl-aix71-ppc64-1 tmp named pipe issue? /tmp//sh-np.mV6aac: ambiguous redirect

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1981]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk16/job/jdk16-aix-ppc64-hotspot/90/consoleFull
```
04:45:02  /opt/freeware/bin/bash: cannot make pipe for process substitution: No such file or directory
04:45:02  /opt/freeware/bin/bash: /tmp//sh-np.mV6aac: ambiguous redirect
```
maybe the sh-np files need cleaning up?

**Comment by sxa** [comment]
Looking at it at the moment I'm not seeing any issues with too many files which would cause that to be a problem (and in theory it would have been resolved by https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/929#issuecomment-772487147 although there are still some from Januaryhave resolved this? inode usage is only at 3%, space 15% so there's no particular known problem on that machine at present (I'm assuming no-one else has done any remidial work since I don't see any other comments in here) ... Re-running at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk16/job/jdk16-aix-ppc64-hotspot/92 on the same machine

**Comment by sxa** [comment]
Attempting a clearup (moving to `/tmp/shnp` and `/tmp/shnpaz` and will re-run if/when it completes)

**Comment by sxa** [comment]
The immediately problem has been resolved. The cron jobs which should perform this cleanup are being updated (and automated via ansble) as there was a bug in them. This is being done under https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2029. The underlying issue for this problem is at https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/929
