### ISSUE TITLE
Ansible request for Scaleway hosts - update sudo version 1.9.5p2 or higher

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#2162]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [X] Request for new playbook addition

Details:

Scaleway recommends we update Sudo to the version above.

**Comment by sxa** [comment]
I believe this relates to https://ubuntu.com/security/notices/USN-4705-1 which is fixed in Ubuntu's sudo version `1.8.16-0ubuntu1.10` which is the one we have on our machines, so no further updates should be needed. Unless there is a belief that this is incorrect (in which case re-open) I'm closing this.
