### ISSUE TITLE
Ansible request for MSVS_2010, Win2012

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#2165]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:
Seems the link we were using to install the MSVS_2010 installer has expired? It gives a 404 error now.

Ref: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/1140/console

Looks like we can install 2012 at oldest now : https://visualstudio.microsoft.com/vs/older-downloads/

**Comment by sxa** [comment]
Since https://github.com/adoptium/temurin-build/pull/2191 was merged I think we may no longer require VS2010 anywhere but it would be useful to confirm this. See also the comment in https://github.com/adoptium/temurin-build/issues/466#issuecomment-634727945 which indicated that was likely the only one left.

**Comment by sxa** [comment]
@andrew-m-leonard This scenario is some more "food for thought" for the work you're doing at the moment :-)

**Comment by Willsparker** [comment]
From what I can gather from looking at those issues and the build repo code, is that MSVS_2010 is no longer used - both JDK8 HS and J9 use `toolchain_version=2013` according to the builds too; so I'll create a PR to remove it :-)
