### ISSUE TITLE
Add printer-driver-cups-pdf and gv to the JCK playbook

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#307]
This will allow the print tests to pass - I've already installed these on the first JCK x64 machine in order to verify that it works - @lumpfish has been able to get the print dialog and perform most of the tests with this configuration.

**Comment by geraintwjones** [comment]
@sxa555 - pull request awaiting your review.
I have tested, and have now re-run the playbook against the JCK machines. The only one that has not been updated is `jck-softlayer-ubuntu1604-x64-2` which AWX can't reach because it's not in KeyBox. I have raised an issue for that (#302) because KeyBox won't allow me to add it. I'm still waiting for that to get some attention.
