### ISSUE TITLE
Document each dependency in the ansible scripts

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#373]
We should say *why* we have them and document the various GCC workarounds etc.

**Comment by sxa555** [comment]
I'd quite like the `name` field to be used with a clear section at the end of each saying what it's needed
e.g. "Install EPEL repository [for subsequent packages]". Using a standard syntax like that would also make it simple to identify the ones we don't have explanations for.

Ideally this could be done by checking the history of the files, although since they were refactored a few months back some of the history will be a bit more difficult to find. So we'd need to look at what happened before these commits:

https://github.com/AdoptOpenJDK/openjdk-infrastructure/commit/a68896479cd05cc7560ee3efdac4bb43e476b1f9#diff-633b6e95ee1459d79fedbdd769e8f0c5 (Linux->Unix rename, Feb 8 2018)
Repo just before that change is at https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/1d5177f14d84adb91e1d2fd31e07c71efb8bee9b


https://github.com/AdoptOpenJDK/openjdk-infrastructure/commit/1dbe068a806542c4e325a707b706757d81895d9f (New playbook layout, December 18, 2017)
Repo just before that change is at https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/396e59e409b8b6d4c2a3cbeb50cc732498fdb2bb

**Comment by sxa555** [comment]
Mostly done now for the main Unix/Windows ones so I'm going to close this - we can improve this as we go forward
