### ISSUE TITLE
Use cygwin git and ssh on Windows, update ansible script & build/test machines 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#378]
From discussion in June 5 infra call, sounded like the ansible script for Windows could use some care and attention.

Currently there are some build and test failures relating to the fact that the Windows machines are not configured with cygwin properly.  

Side-effects of this misconfiguration means that some builds fail, and some openjdk regression tests (that call .sh scripts) can not be run (or they fail).

It is important to correct this so we have reliable build and test on the Windows platform.

**Comment by AdamBrousseau** [comment]
The playbooks already have cygwin.
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

I think the issues we've been seeing are at least partly because they also have Windows Git (& Git Bash) which is not needed imo (please object if I am wrong) and this can get the PATH out of sorts.
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GIT/tasks/main.yml

I believe we should
-  Remove Windows git completely, and use cygwin git. 
- Change the connection protocol of the machines from JNLP to ssh (cygwin)

The *main reason for the protocol change is because JNLP requires either a human login to the slave and connect it to the master or some extra setup on the slave to run a service to do it automatically. If you connect over ssh, there is no extra manual effort or setup required on the machine.

We have switched to the above setup at Eclipse/OpenJ9 and things are much more stable now.

Related #376 #373 eclipse/openj9#2063
PS. Sorry @smlambert I may have hijacked your issue slightly

**Comment by sxa555** [comment]
> Windows machines are not configured with cygwin properly.
Not to my knowledge - it's always been there and configured on all the machines

The windows ansible issues are not related to cygwin

**Comment by llxia** [comment]
Windows configuration issue is blocking us to complete [Add AdoptOpenJDK test pipelines into nightly build ](https://github.com/eclipse/openj9/issues/2037) in Eclipse OpenJ9 Jenkins. From what I have tested, I can run .sh scripts in Eclipse OpenJ9 windows machine, but I cannot run the [same script ](https://github.com/AdoptOpenJDK/openjdk-tests/pull/460)using AdoptOpenJDK windows machine.

Link to OpenJ9 win build: https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK8-win_x86-64_cmprssptrs/29/
Link to AdoptOpenJDK win build: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox2/246/console

**Comment by AdamBrousseau** [comment]
What do we need to do to resolve this issue? It's causing a number of downstream problems and blocking other issues from being resolved. I'm not sure if the lack of movement is because a lack of priority or if it's unclear what the next steps are or who should be taking them.

**Comment by sophia-guo** [comment]
See the comment on https://github.com/AdoptOpenJDK/openjdk-tests/issues/499 I believe that recently enabled new Windowns machine azure: win2012r2-x64-1: {ip: 13.68.134.204, user: adoptopenjdk} do not have this issue. So again question would be "any difference between azure and packet especially configuration with cygwin or jenkins?" Could we configure them in a same way?

**Comment by llxia** [comment]
I ran a jdk_math using .sh from my local branch on new windows machine `test-azure-win2012r2-x64-1` and it passed: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/466/

Currently, I am running sanity functional to verify: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/467

If everything is ok, I think we should disable the incorrectly configured machine `test-packet-x64-windows-2012r2-1` and deliver the change to use same script.

**Comment by smlambert** [comment]
So, I have disabled test-packet-x64-windows-2012r2-1 as its configuration is 'off-brand' from the expected configuration in ansible scripts and defacto standard for test machines at Adopt.  

We should recycle test-packet-x64-windows-2012r2-1, as it is not useful/usable.  It would be good to get another windows test machine set up (and configured in the same way the test-azure-win2012r2-x64-1 is, as that is usable).

**Comment by sxa555** [comment]
Just gone back onto the machine and `/usr/bin` appears pretty much at the start of the PATH (Just after `/usr/local/bin` from a new cygwin shell, so we might be ok now. WIll re-enable and see if anything breaks on it ...

**Comment by Willsparker** [comment]
Windows playbook has been updated enough to get JDK8 working, at least. Through my testing, it seems Cygwin's `git` is preferable generally as Windows `git` will have issues when interacting with Cygwin: https://github.com/git-for-windows/git/issues/568 
Just as an FYI :-)

**Comment by karianna** [comment]
I think we can call this done and raise individual issues as needed.   Thanks @Willsparker
