### ISSUE TITLE
Automate Cleaning up bad Java Processes from jenkins followers

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#419]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/487 - covers AIX but this issue actually probably occurs on all test hosts.

- [x] test-azure-win2012r2-x64-1 
- [x] test-macincloud-macos1010-1
- [x] test-macincloud-macos1010-2
- [x] test-marist-ubuntu1604-s390x-1
- [x] test-osuosl-ppc64le-ubuntu-16-04-1
- [x] test-osuosl-ppc64le-ubuntu-16-04-2
- [x] test-packet-armv8-ubuntu-16-04
- [x] test-packet-ubuntu1604-x64-1
- [x] test-packet-ubuntu1604-x64-2
- [x] test-packet-ubuntu1604-x64-3
- [x] test-packet-ubuntu1604-x64-4
- [x] test-packet-x64-windows-2012r2-1
- [x] test-scaleway-ubuntu1604-x64-1
- [x] test-softlayer-rhel69-x64-1
- [x] test-softlayer-rhel74-x64-1
- [x] test-softlayer-ubuntu1604-x64-1

**Comment by sxa555** [comment]
Added this comment to the other item, but since they are RMI tests so are initiated as background processes it's probably worth having the jobs check for any abandoned RMI processes at the start of the run, report on them, and kill them off before running the new tests.

(Or it could be done with a regular running jenkins job across all the machines - as long as there is only one executor on each machine either method should be safe to do)

**Comment by karianna** [comment]
OK, they're all manually cleared down.  Keeping this open for someone to create a cleanup job

**Comment by sxa555** [comment]
This has been kicking around for a while in the WIP tab but is now live ... Will leave it a few days before enabling the option that lets it kill stuff (with yellow triangle warnings if it needed to do anything):

https://ci.adoptopenjdk.net/view/Tooling/job/SXA-processCheck/
