### ISSUE TITLE
Access required for adopt JCK machines for ppcle and linux_x86 the large heap

### ISSUE THREAD

**Issue by suman-mitra** [AdoptOpenJDK/openjdk-infrastructure#426]
To do adopt JCK interactives need access for ppcle and linux_x86 large heap machines.Please provide the list of machines as well.Access is required for Vaishnavi Pathipati/India/IBM@IBMIN(vaipathi@in.ibm.com) and Suman Mitra/India/IBM@IBMIN(summitra@in.ibm.com)

**Comment by lumpfish** [comment]
The machines list can be found at under the -jck stanza: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/inventory.yml.
Rather than having individual userids we may use a shared 'jcktester' userid for this testing, in which case a member of the infrstructure team will privately give you that user's password in order to execute the tests.

**Comment by mleipe** [comment]
Are we not using KeyBox to manage access here?  @sxa555?

**Comment by sxa555** [comment]
> 
> Are we not using KeyBox to manage access here? @sxa555?
Not for these systems and accounts at present, no.

**Comment by sxa555** [comment]
I'm not sure if Vaishnavi has been authorized to access the JCK at adoptopenjdk, so unless that has already been done I cannot grant them access. I have requested Suman's public ssh key in order to grant access.

**Comment by sxa555** [comment]
Key added to `159.122.210.205` (xLinux) and `140.211.168.225` (pLinux). You should be able to log in as `jcktestr` on both machines

**Comment by lumpfish** [comment]
On unix, rather than receiving the password, the current process is to provide the infrastructure team with a user's ssh key.  Once processed this will enable the user to login to the jck test machines as jcktester.
For Windows, where RemoteDesktop is used to run the test the process is currently for the user to be given current the jcktester password.

**Comment by karianna** [comment]
Do we have both of these folks added on Slack and the appropriate GitHub team?  I assume a JCK signee can vouch for both of these?  Just making sure of the audit trail :-)

**Comment by lumpfish** [comment]
Yes, @suman is already in the JCK team at AdoptOpenJDK and Vaishnavi works with us both at IBM.  Do you need Vaishnavi's github id - I see we don't have that atm.

**Comment by karianna** [comment]
Yes please

**Comment by lumpfish** [comment]
Vaishnavi's github id is vaishnavipathipati

**Comment by karianna** [comment]
@vaishnavipathipati has been added to the JCK team in GitHub

**Comment by karianna** [comment]
@sxa555 Over to you I think?  I'm not in the infra team so can't give access (I don't think)

**Comment by sxa555** [comment]
Yep I've just been given his ssh key so I'll grant access now - thanks @karianna

**Comment by sxa555** [comment]
Access granted to the `jcktestr` account on a Linux/ppcle JCK machine and a Linux/x86-64 - both have been marked offline in jenkins while the manual testing is executed.

**Comment by lumpfish** [comment]
jcktestr, not jcktester (which is what I created on the Windows machines)?

**Comment by lumpfish** [comment]
@sxa555 , please can I have access too so I can help with the testing.  How should I provide my ssh key?
