### ISSUE TITLE
Install gcc 7.3.0 on all Linux build machines

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#438]
Oracle is starting to build with gcc 7.3.0 so we should install this on our Linux build machines.
Ref: https://bugs.openjdk.java.net/browse/JDK-8200375

Source: ftp://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-7.3.0/gcc-7.3.0.tar.xz
ccache update source: https://www.samba.org/ftp/ccache/ccache-3.4.2.tar.xz

**Comment by sxa555** [comment]
My current plan is to build from source on each of the three platforms (Linux on `x64`, `ppc64le` and `s390x`) with `--prefix=/usr/loccal/gcc --program-suffix=-7.3` then create a tarball of the `/usr/local/gcc` directory that we can use to deploy via ansible in order to save the large amount of time to compile from source on each ansible run.

**Comment by sxa555** [comment]
Build machines for the compiler:
x86: build-joyent-centos69-x64-1
ppc64le: build-osuosl-centos74-ppc64le-2
s390x: build-marist-rhel74-s390x-1

**Comment by jdekonin** [comment]
How are these tarballs going to be more convenient than pulling from a repo?  What is the plan for storage/access for users of the playbooks?
Related PRs #441 (ubuntu) and #442 (centos)

**Comment by sxa555** [comment]
@jdekonin Are you aware of any official (trustworthy) repo for gcc 7.3.0?

**Comment by jdekonin** [comment]
Not one source for all platforms I don't no.  There might be architectures and operating systems that won't have pre-built packages, that we will need to compile from sources, sles11 for example.  But from what I have seen there are pre-built packages for x,p,z,arm for ubuntu, redhat and centos available.  I don't see why we wouldn't take advantage of installing the gcc7 (and support packages) just as we would wget.

**Comment by vsebe** [comment]
The gcc 7.3 requires a newer linker - `ld` - version (at least on CentOS 6 and RHEL 6) which is included in the [devtoolser-7](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/) packages, see devtoolset-7-binutils. devtoolset-7 would resolve and install all required dependencies.
It also makes it easier to switch between the gcc 4.8 and 7.3 toolchain environments as they will coexist for awhile.

**Comment by sxa555** [comment]
@jdekonin Where are the RHEL/CentOS packages you've seen for p/z?
@vsebe I'm aware of the devtoolset-2 packages but I'm not sure if they're available for non-x86 architectures and I'm nervous about having different setups on the machine across architectures

**Comment by sxa555** [comment]
I'm not sure if our RHEL7/s390x machines are configured in a way that will allow that.
But we are using CentOS on ppc64le, so my preference would likely be to do it consistently unstalling under `/usr/local/gcc` from source across platforms, since unless someone doing it for themselves on anything other than x86-64 (where they could get it from a CentOS RHEL or similar) has a RHEL subscription it will prevent them from accessing the devtoolset repos.

**Comment by sxa555** [comment]
(If - as mentioned by @vsebe earlier - we need an additional later `ld` that will impact the solution for x86-64 where we build on v6, so on there it may make sense to do it via devtoolset-2 even though the installation is could be more fiddly for the end user)

**Comment by vsebe** [comment]
@sxa555 @jdekonin - For RHEL7/ppcle the [IBM Advanced toolchain for Linux on Power](https://developer.ibm.com/linuxonpower/advance-toolchain/advtool-installation/) provides a self-contained toolchain, similar to devtoolset-7 for x86. It can be installed via yum, rpm or manually (using  Advance Toolchain (AT) downloader tool). See detailed instructions on: https://developer.ibm.com/linuxonpower/advance-toolchain/advtool-installation/.
Advance toolchain 11.0-3 comes with:
- gcc 7.3.1 20180207 (Advance-Toolchain-at11.0) [ibm/gcc-7-branch revision 257393](gcc, c++/g++, libstdc++-v3)
- GNU Binutils - 2.29
- performance and debugging tools
The [Release notes](ftp://ftp.unicamp.br/pub/linuxpatch/toolchain/at/redhat/RHEL7/at11.0/release_notes.at11.0-11.0-3.html) provides further details.
It has a modulefile that enables the environment to gcc 7.3. This would allow easily to switch between gcc 4.8 and gcc 7.3 environments.

It installs in  `/opt` like devtoolset-7 on x86.
To enable the gcc 7.3 environment just run: `module load at11.0` (devtoolset-7: `scl enable devtoolset-7 bash`). To disable and return to the system environment run:  `module unload at11.0` (devtoolset-7: exit the bash to return to original environment).

**Comment by jdekonin** [comment]
Looks like the advanced toolchain is across operating systems too, with the exception of ubuntu18.

**Comment by sxa555** [comment]
Hmmm wasn't aware of that toolchain before, although that would mean we ended up with three different solutions - one for each of `x86`, `ppc64le` and `s390x`

**Comment by karianna** [comment]
I'll add my 2c on my philosophy of maintaining packages for build/test machines:

Build and Test hosts should have a known, good set of packages at set versions that we can produce repeatable builds from.  That typically means we have to protect ourselves against O/S package updates due to security and stability patch cycles.

**Philosophy 1:** Never have the build / test scripts rely on default packages which can get upgraded underneath them!

**Proposed Solution(s):**  Install versioned packages in a consistent (within each platform) **non-default** location.  Ensure that the build/test scripts reference those versioned libs directly **or** create symlinks so that if the regular package is called it calls the versioned one we want instead (this assumes package managers don't override the symlink when upgrading the default package).

**Philosophies 2&3:** Prefer the official (or defacto) package repository for packages on a per platform as they're likely to be better tested and more trustworthy.  Only consider a cross platform solution if it is an official or defacto std.

**Proposed Solution(s):**  If ansible can support the official / defacto repository for a package for a particular platform, then use that. Else use a cross platform solution if there's strong defacto support for it. Else build the package from source (making sure that we checksum / security check the source) and store the resulting binary (with checksum) on our own repository (which we need to decide whether it is CI, GitHub or Ansible Tower).

Thoughts on that as a policy?

**Comment by sxa555** [comment]
While ideal, I think (1) May be difficult since that would imply not allowing things like `make` to be upgraded.

Otherwise it seems reasonable, but that means not using the [IBM advance toolchain](https://developer.ibm.com/linuxonpower/advance-toolchain/advtool-installation/) as its' not an "official/defacto" repository, so we're down to source builds on pLinux/zLinux.  At the moment the adoptopenjdk RedHat build machines have been tested using gcc 7.3 built from source on x/p/zLinux although we should be able to switch the x86-64 ones to using the `devtoolset-7` repository if we go down that route.

**Comment by karianna** [comment]
@sxa555 I think using IBM's toolchain is OK.  I've updated Philosophies 2&3.

**Comment by sxa555** [comment]
All the main architectures are done, so I'll close this and leave #475 which is still awaiting an arm32 version
