### ISSUE TITLE
Windows hosts missing x86_64-w64-mingw32-g++

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#490]
Just saw this on build-softlayer-win2012r2-x64-2 when building jdk10u-openj9 which failed the build:

x86_64-w64-mingw32-g++: Command not found

-----

For older toolchain versions - VS2010, VS2013 - the [mingw64-x86_64-gcc-g++](https://cygwin.com/packages/x86_64/mingw64-x86_64-gcc-g++/mingw64-x86_64-gcc-g++-5.4.0-3) package available with cygwing works fine.

The openjdk10_openj9_build_x86-64_windows uses VS2013: `--with-toolchain-version=2013 `

```
Running ./configure with arguments ' --with-version-pre=adoptopenjdk --with-version-string=10.0.2+13  --with-boot-jdk=/cygdrive/c/openjdk/jdk9 --with-freetype-src=/cygdrive/c/openjdk/freetype-2.5.3 --with-toolchain-version=2013 --with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --disable-ccache --with-milestone=fcs'

```
`x86_64-w64-mingw32-g++` should have been installed with cygwin and be available in `/usr/bin` (Linux path) or `C:\cygwin64\bin` (Windows path) . More details about OpenJ9 extensions for OpenJDK10 build on Windows could be found [here](https://github.com/eclipse/openj9/blob/master/buildenv/Build_Instructions_V10.md#windows).

**Comment by karianna** [comment]
@ali-ince Are you able to take a look - this only recently failed...

**Comment by sxa555** [comment]
This is tied in with #448 #422

**Comment by sxa555** [comment]
Have added VS2017 an the appropriate MInGW to https://ci.adoptopenjdk.net/computer/build-softlayer-win2012r2-x64-2 as described in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/448.
Test build ran through at https://ci.adoptopenjdk.net/job/build_ao11j9_win_vs2017/1, therefore closing (although the updated compiler and MInGW will need to be put on the other build machines too, although there is some discussion over whether Clang will be used instead of MinGW)
