### ISSUE TITLE
New OpenJ9 compile requirement for x86: nasm

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#492]
This is specific to feature work surrounding https://github.com/eclipse/openj9/issues/2418

@nbhuiyan, can you please advise as to which version of nasm OpenJ9 requires?

**Comment by nbhuiyan** [comment]
@jdekonin The version of nasm we'd like is the current latest release: v2.13.03

**Comment by sxa555** [comment]
@nbhuiyan Does your earlier comment mean that we definitely cannot use the ones supplied with the OS (2.07 in this case) is definitely not an option?

**Comment by nbhuiyan** [comment]
@sxa555 We MAY be able to use nasm v2.07, but I have never tested using that version. The oldest version I have successfully tried building and testing with is v2.11.08. The reason we are setting a newer version as a requirement is that one of the motivations behind making a switch to NASM was to be able to use newer instructions and features available through a modern assembler. NASM v2.07 is [almost a decade old](http://repo.or.cz/nasm.git/tag/6ac396e0714fa3b0b6c0fa476a8f7fea4a3221a3), and a lot has been [fixed/added](https://www.nasm.us/doc/nasmdocc.html) since then.

**Comment by sxa555** [comment]
OK ... just a shame not to use the default on the distribution, but as long as it doesn't introduce any extra runtime dependency I'm happy with using it. Thanks

**Comment by AdamBrousseau** [comment]
Resolved via #494 I believe.
