### ISSUE TITLE
Variables missing from playbooks when normal user executes

### ISSUE THREAD

**Issue by CJKwork** [AdoptOpenJDK/openjdk-infrastructure#532]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/group_vars/all/adoptopenjdk_variables.yml

Under Nagios variables, `provider` and `ansible_port` variables are missing when using a custom host list.

**Comment by sxa555** [comment]
We should either:

1. have a check in there with a message to the user on how to add suitable ones 
2. Default the values
3. Skip the sections (with a warning) if they are not set

**Comment by sxa555** [comment]
3 should be possible with appropriate ansible flags - perhaps something like this (full list TBC)

` --skip-tags="install_zulu,jenkins_authorized_key,nagios_add_key,add_zeus_user_key,jenkins_user,security,build_tools_jfx"`

**Comment by sxa555** [comment]
Could also do with:
- Option to NOT remove any system installed packages when we build others from source `no_remove_system` (Or I suppose `cleanup_system` since it's a `--skip` parameter)
- Have separate `build` and `test` options across the playbooks so that noly the appropriate bits are installed

**Comment by sxa555** [comment]
`s/add_zeus_user_key/superuser/`
