### ISSUE TITLE
Get macos playbooks production ready

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#554]
Initial work is at https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/219

**Comment by jdekonin** [comment]
I have some instructions on this as well for newer systems (10.13.6), what I used as an install base.  I'll forward to @cwillhelm.  My instructions are based on building JDK8 and JDK11 with OpenJ9 though.  This should be sufficient to cover openjdk requirements as well, since OpenJ9 start with openjdk system requirements + add-ons.  I'll document those add-ons where I know them.

**Comment by jdekonin** [comment]
Please make sure curl is also included in the playbook as per #404.

**Comment by sxa555** [comment]
Going to close this as a duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/212 (will transfer the comment about curl to that issue)
