### ISSUE TITLE
Get AIX playbooks production ready

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#562]

**Comment by CJKwork** [comment]
A number of changes made:
Scripts changed:
aix.yml
nagios/nagios_aix.yml

new ksh script:
scripts/AIX_ramdisk.ksh

Changes:

We now load standard variables from adoptopenjdk_variables.yml

Checks for bash and if not there, installs it 

Have added the RAM disk stuff

Now do extra checking for the existence of stuff before trying to install - e.g.
openssl
X11.adt.ext

Move the CPAN section to after the jenkins user home directory has been created, as it refers to it.

Corrected a syntax error in the swap size configuration section.

Now loads the Zeus User ssh key from /Vendor_Files/keys/zeus.key (was /home/ubuntu/keys/zeus.key)

Now loads /usr/local/nagios/libexec/ from /Vendor_Files/aix/nagios/ (was /home/ubuntu/aix/nagios/)

Now loads nagios User ssh key from /Vendor_Files/keys/nagios.key (was /home/nagios/key/id_rsa.pub)

**Comment by sxa555** [comment]
Thanks @CJKwork - I'll speak to you on Monday and we can try running a build on a machine that's been set up with your modifications and see if anythign else is missing :-)

**Comment by sxa555** [comment]
TODO: Add java 10, java 11 (and maybe java 9!) to the machine as well - similar to the adoptopenjdkXX roles in the Unix playbook.

**Comment by sxa555** [comment]
@CJKwork FYI I've confirmed with John who wrote the original playbooks that the `/Vendor_Files/aix` directory was only ever tested internally and not deployed on the adoptopenjdk infrastructure (which explains my inability to find it along with the other `Vendor_Files`!) so we'd need to put that in place (subject to licensing etc.) before we'd be able to deploy on the adoptopenjdk infrtastructure.

**Comment by sxa555** [comment]
@adamfarley mentioned that he's currently collating a list of things he's needed to put on a AIX box so he's going to add a comment here with a list of the things he's had to install ... Would be good to ensure that everything from his list is included in this playbook.

**Comment by adamfarley** [comment]
@CJKwork - Here's the list of things I came up with:

1. X11.adt.ext may already be installed. To check, use this command: lslpp -l | grep "X11.adt.ext"

2. yum_install_aix-ppc64.txt has been relocated to: https://github.com/eclipse/openj9/blob/master/buildenv/aix/jdk10/yum_install_aix-ppc64.txt

3. I advise using the raw link instead of the github html link, to prevent some fool (definitely not me) running wget and trying to "yum shell" a file full of html.

https://raw.githubusercontent.com/eclipse/openj9/master/buildenv/aix/jdk10/yum_install_aix-ppc64.txt

4. The instructions for getting freemarker didn't work for me. I had to use:

cd /<my_home_dir>
wget --no-check-certificate https://sourceforge.net/projects/freemarker/files/freemarker/2.3.8/freemarker-2.3.8.tar.gz/download -O freemarker.tgz
gunzip -c freemarker.tgz | tar -xzf -
rm -f freemarker.tgz
mv freemarker-2.3.8/lib/freemarker.jar .
rm -rf freemarker-2.3.8

5. The following packages may need to be installed or upgraded
autoconf
coreutils - Note that you may need to uninstall mktemp first, to prevent conflicts. Don't worry, as coreutils supplies a replacement mktemp.
grep
fontconfig-devel
tar
git
curl
ca-certificates

6. Add these two locations to *start* of the path, if they are not already:
/opt/freeware/bin
/opt/IBM/xlC/13.1.0/bin           (Or wherever xlc_r is located. "find / -name xlc_r" is helpful)

7. And also either the jdk location, or add --with-boot-jdk to the configure line.

8. Due to the size of one of the files, the initial extensions clone had to be performed by downloading and unpacking the zip.

9. If you get an out of memory error, it's worth running these commands as root:
ulimit unlimited
ulimit -m unlimited
ulimit -d unlimited
ulimit -u unlimited
ulimit -n unlimited

10. I understand work is afoot to update the AIX build instructions, so you may find more help there in the near future.

**Comment by sxa555** [comment]
@CJwork the following commands should allow you ro run a build of JDK8/HotSpot - I'd recommend running as tjhe `jenkins` user and in a director under `/ramdisk0` which is owned by `jenkins`
```
git clone https://github.com/AdoptopenJDK/openjdk-build
cd openjdk-build
./makejdk-any-platform.sh --jdk-boot-dir /home/bootjdk/j2sdk-image --configure-args "-with-memory-size=18000 --with-cups-include=/opt/freeware/include --with-extra-ldflags=-lpthread --with-extra-cflags=-lpthread --with-extra-cxxflags=-lpthread" --skip-freetype jdk8u
```
And then to test JDK11 with OpenJ9 start again with
```
git clone https://github.com/AdoptopenJDK/openjdk-build
cd openjdk-build
./makejdk-any-platform.sh --jdk-boot-dir <wherever_adoptopenjd10_is> --configure-args  "--disable-warnings-as-errors --with-memory-size=18000 --with-cups-include=/opt/freeware/include --disable-warnings-as-errors" --skip-freetype --use-jep319-certs --build-variant openj9 jdk11u
```
