### ISSUE TITLE
AWX breakage on test-packet-ubuntu1604-x64-2 in remove the old ant action

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#572]
https://ansible.adoptopenjdk.net/#/jobs/88515/#followAnchor

```
TASK [ant : Remove the older Ant package] **************************************
13:29:21
fatal: [test-packet-ubuntu1604-x64-2]: FAILED! => {"changed": false, "failed": true, "msg": "python2 bindings for rpm are needed for this module. python2 yum module is needed for this  module"}

```

**Comment by sxa555** [comment]
Not sure that message is especially helpful but here's what I get when I try and remove it manually:

```
root@test-packet-ubuntu1604-x64-2:~# dpkg -r ant
dpkg: dependency problems prevent removal of ant:
 ant-contrib depends on ant.
 ant-optional depends on ant (= 1.9.6-1ubuntu1.1).

dpkg: error processing package ant (--remove):
 dependency problems - not removing
Errors were encountered while processing:
 ant
root@test-packet-ubuntu1604-x64-2:~# 
```
SInce we have a [separate Ant-contrib role](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml) to install into `/usr/local/` I suspect these can be removed. Will submit a PR to do this.

**Comment by sxa555** [comment]
Oh hang on - the role appears to be trying to remove via yum not apt even on Ubuntu which probably explains the seemingly unclear message
