### ISSUE TITLE
Synchronise hostnames across jenkins/inventory.yml/anywhere else

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#619]
Example: [test-osuosl-ppc64le-ubuntu-16-04-1](https://ci.adoptopenjdk.net/computer/test-osuosl-ppc64le-ubuntu-16-04-1/) is shown as `test-osuosl-ubuntu1604-ppc64le-1` in [inventory.yml](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/inventory.yml)

There are likely more examples. Makes it awkward to run the inventories against a specific machine when someone requests it (generally with a name from Jenkins)

**Comment by HusainYusufali** [comment]
Pull request opened to update the inventory.yml file to match the jenkins hosts. https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/634

**Comment by HusainYusufali** [comment]
Below is a list of changes that need to be created in order to synchronize the hosts across Jenkins and the Inventory.yml. @sxa555 can you please review this before I go ahead and make the changes

| Current Name In Jenkins  | New Name in Jenkins |
| ------------- | ------------- |
| build-macstadium-macos1010-1 | build-macstadium-macos1010-x64-1 |
| build-macstadium-macos1010-2 | build-macstadium-macos1010-x64-2 |
| test-macincloud-macos1010-1 | test-macincloud-macos1010-x64-1 |
| test-macincloud-macos1010-2 | test-macincloud-macos1010-x64-2 |
| build-osuosl-ppc64-aix-71-1 | build-osuosl-aix71-ppc64-1 |
| build-osuosl-ppc64-aix-71-2 | build-osuosl-aix71-ppc64-2 |
| test-osuosl-ppc64le-ubuntu-16-04-1 | test-osuosl-ubuntu1604-ppc64le-1 |
| test-osuosl-ppc64le-ubuntu-16-04-2 | test-osuosl-ubuntu1604-ppc64le-2 |
| test-packet-armv8-ubuntu-16-04 | test-packet-ubuntu1604-armv8-1 |
| test-packet-x64-windows-2012r2-1 | test-packet-win2012r2-x64-1 |
| build-marist-s390x-sles-12 | build-marist-sles12-s390x-1  |
| build-marist-s390x-zOS-1 | build-marist-zos21-s390x-1 |
| build-marist-s390x-zOS-2 | build-marist-zos21-s390x-2 |
| build-scaleway-x64-ubuntu-16-04-2 | build-scaleway-ubuntu1604-x64-2 |
| build-scaleway-armv7-ubuntu16-04-1 | build-scaleway-ubuntu1604-armv7-1 |
| build-scaleway-armv7-ubuntu16-04-2 | build-scaleway-ubuntu1604-armv7-2 |


| Jenkins machines to be added to inventory  |
| ------------- |
| build-plymouth-x64-solaris11-1 |
| build-sxa-armv7-raspbian |
| test-marist-s390x-sles-12 |
| test-marist-sles12-s390x-1 |
| build-scaleway-armv7-ubuntu16-04-1-temp |
| build-scaleway-armv7-ubuntu16-04-2-temp |
| test-softlayer-win2012r2-x64-1 |

**Comment by karianna** [comment]
I have to question the two temp machines on scale way - who set those up and for what purpose?

**Comment by karianna** [comment]
the test-marist labels seem mixed up as well.

**Comment by HusainYusufali** [comment]
Some of the machines are named incorrectly in contrast to the labels they have. The changes that need to be made are listed below and updated in the table above in bold. In regards to the scaleway temp machines I do not have any information on that.

https://ci.adoptopenjdk.net/computer/test-marist-sles12-s390x-1/ is build machine based on its labels, requires a name change, and IP changed in the inventory file
https://ci.adoptopenjdk.net/computer/build-marist-s390x-sles-12/ is a test machine based on its labels, requires a name change, and added to the inventory file
https://ci.adoptopenjdk.net/computer/test-marist-s390x-sles-12/ is a test machine, requires a name change, and added to the inventory file

**Comment by sxa555** [comment]
Most of the issues with the marist sles 12 machine(s) was resolved under #765.
@Willsparker This could do with being revisited. `inventory.yml` is the master list of all our machines and is processed by ansible tower when deciding which machines to configure. This issue is mostly surrounding the fact that not all of the names on there match the ones used in https://ci.adoptopenjdk.net/computer/

**Comment by Willsparker** [comment]
All of the hostnames I've found that were out of sync between `ci.adoptopenjdk.net` and `inventory.yml`

| Jenkins | Inventory.yml |
| --- | --- |
| build-macstadium-macos1010-1  | build-macstadium-macos1010-x64-1 |
| build-macstadium-macos1010-2 | build-macstadium-macos1010-x64-2 |
| build-macstadium-macos1012-1 | build-macstadium-macos1012-x64-1 |
| build-macstadium-macos1012-2 | build-macstadium-macos1012-x64-2 |
| build-marist-s390x-zOS-1 | build-marist-zos21-s390x-1 |
| build-marist-s390x-zOS-2 | build-marist-zos21-s390x-2 |
| build-osuosl-ppc64-aix-71-1 | build-osuosl-aix71-ppc64-1 |
| build-osuosl-ppc64-aix-71-2 | build-osuosl-aix71-ppc64-2 |
| build-packet-ubuntu1604-armv7l-1 | **Missing from Inventory.yml** |
| build-packet-ubuntu1604-armv8l-1 | **Missing from Inventory.yml** |
| build-scaleway-x64-ubuntu-16-04-2 | build-scaleway-Ubuntu1604-x64-2 |
| build-scaleway-armv7-ubuntu16-04-2 | build-scaleway-ubuntu1604-armv7-1 |
| build-scaleway-armv7-ubuntu16-04-1 | build-scaleway-ubuntu1604-armv7-2 |
| test-godaddy-win3 | test-godaddy-win2016-x64-3 |
| test-osuosl-ppc64-aix-71-1 | test-osuosl-aix71-ppc64-1 |
| **Missing from Jenkins** | test-osuosl-aix71-ppc64-2 |
| test-packet-armv8-ubuntu-16-04 | test-packet-ubuntu1604-armv8-1 |
| test-packet-x64-windows-2012r2-1 | test-packet-win2012r2-x64-1 |
| test-marist-ubuntu1604-s390x-2-XJ | **Missing from Inventory.yml** |
| **Missing from Jenkins** | test-softlayer-win2012r2-x64-1 |

**Comment by sxa555** [comment]
Notes:
- build-packet-ubuntu1604-armv8l-1 and the armv7l one are the same machine (It's really armv8 but was intended to be used for 32-bit builds - probably needs to only have the armv8 definition since that's what it really is https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/630
- test-godaddy-win3 doesn't work if I rename it to the correct name in jenkins (!) https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/827#issuecomment-512336767
- test-osuosl-aix71-ppc64-2 isn't set up yet so it's status is correct https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/146
- test-marist-ubuntu1604-s390x-2-XJ is the machine formerly known as jck-ubuntu1604-s390x-2 so needs updating in `inventory.yml` https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/610#issuecomment-503201361

**Comment by karianna** [comment]
> All of the hostnames I've found that were out of sync between `ci.adoptopenjdk.net` and `inventory.yml`
> 
> Jenkins	Inventory.yml
> build-macstadium-macos1010-1	build-macstadium-macos1010-x64-1
> build-macstadium-macos1010-2	build-macstadium-macos1010-x64-2
> build-macstadium-macos1012-1	build-macstadium-macos1012-x64-1
> build-macstadium-macos1012-2	build-macstadium-macos1012-x64-2
> build-marist-s390x-zOS-1	build-marist-zos21-s390x-1
> build-marist-s390x-zOS-2	build-marist-zos21-s390x-2
> build-osuosl-ppc64-aix-71-1	build-osuosl-aix71-ppc64-1
> build-osuosl-ppc64-aix-71-2	build-osuosl-aix71-ppc64-2
> build-packet-ubuntu1604-armv7l-1	**Missing from Inventory.yml**
> build-packet-ubuntu1604-armv8l-1	**Missing from Inventory.yml**
> build-scaleway-x64-ubuntu-16-04-2	build-scaleway-Ubuntu1604-x64-2
> build-scaleway-armv7-ubuntu16-04-2	build-scaleway-ubuntu1604-armv7-1
> build-scaleway-armv7-ubuntu16-04-1	build-scaleway-ubuntu1604-armv7-2
> test-godaddy-win3	test-godaddy-win2016-x64-3
> test-osuosl-ppc64-aix-71-1	test-osuosl-aix71-ppc64-1
> **Missing from Jenkins**	test-osuosl-aix71-ppc64-2
> test-packet-armv8-ubuntu-16-04	test-packet-ubuntu1604-armv8-1
> test-packet-x64-windows-2012r2-1	test-packet-win2012r2-x64-1
> test-marist-ubuntu1604-s390x-2-XJ	**Missing from Inventory.yml**
> **Missing from Jenkins**	test-softlayer-win2012r2-x64-1

Can we automate that?

**Comment by sxa555** [comment]
> Can we automate that?
Should be able to put together a job that does a check and passes/fails based on whether they're in sync without too much difficulty. Can do that after we do the one-off cleanup ...

**Comment by sxa555** [comment]
Also https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-processCheck should have pretty much the same list of machines

**Comment by Willsparker** [comment]
@karianna  @sxa555 Is a one-off cleanup still required, and if so where should I take the hostnames from?

**Comment by karianna** [comment]
> @karianna @sxa555 Is a one-off cleanup still required, and if so where should I take the hostnames from?

I'll defer to @sxa on this one

**Comment by sxa** [comment]
Let's make them consistent, so `<use>-<provider>-<os>-<arch>-<count>` as far as practical.

**Comment by Willsparker** [comment]
I've changed the following at ci.adoptopenjdk.net, FYI:
```
test-packet-x64-windows-2012r2-1 	---> 	test-packet-win2012r2-x64-1
test-packet-armv8-ubuntu-16-04		--->	test-packet-ubuntu1604-armv8-1
test-ibm-ppc64-aix-71-2 		--->	test-ibm-aix71-ppc64-2
test-ibm-ppc64-aix-71-1 		---> 	test-ibm-aix71-ppc64-1
test-ibm-cabbage			---> 	test-ibm-aix71-ppc64-3
test-godaddy-win3			---> 	test-godaddy-win2016-x64-3
perf-macstadium-macos1015-2		--->	perf-macstadium-macos1015-x64-2
perf-macstadium-macos1015-2		--->	perf-macstadium-macos1015-x64-1
infra-vagrant-1				--->	infra-softlayer-ubuntu1804-x64-1
build-scaleway-x64-ubuntu-16-04-2 	--->	build-scaleway-ubuntu1604-x64-1
build-scaleway-armv7-ubuntu16-04-2	--->	build-scaleway-ubuntu1604-armv7-2
build-scaleway-armv7-ubuntu16-04-1	--->	build-scaleway-ubuntu1604-armv7-1
build-osuosl-ppc64-aix-71-2		--->	build-osuosl-aix71-ppc64-2
build-osuosl-ppc64-aix-71-1		--->	build-osuosl-aix71-ppc64-1
build-marist-s390x-zOS-2		--->	build-marist-zOS-s390x-2
build-marist-s390x-zOS-1		--->	build-marist-zOS-s390x-1
build-macstadium-macos1014-2		--->	build-macstadium-macos1014-x64-2
build-macstadium-macos1014-1		--->	build-macstadium-macos1014-x64-1
build-macstadium-macos1012-1		--->	build-macstadium-macos1012-x64-1
build-macstadium-macos1010-1		--->	build-macstadium-macos1010-x64-1
```

**Comment by Willsparker** [comment]
Of all the hosts that are currently offline at ci.adoptopenjdk.net, the follow are 'unpingable'
```
build-godaddy-rhel7-x64-1
build-linaro-centos74-armv8-1 	( build-linaro-centos74-armv8-2 had same IP )
build-linaro-centos76-armv8-2
build-marist-ubuntu1604-s390x-2
build-marist-ubuntu1604-s390x-3
docker-aws-ubuntu1604-x64-0
infra-aws-ubuntu1804-x64-1
test-macincloud-macos1014-x64-3
test-osuosl-centos74-ppc64le-3
```

**Comment by sxa** [comment]
`test-godaddy-win3` to `test-godaddy-win2016-x64-3` [may be problematic](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/827#issuecomment-512336767)

**Comment by Willsparker** [comment]
Can we confirm that's still an issue? It's been quite awhile

**Comment by sxa** [comment]
Feel free to verify

**Comment by Willsparker** [comment]
I would love to, but none of them are connected to Jenkins, nor do I have credentials for them. They're also not displaying `clock time` or `response difference` which I think is a show that they're turned off at the minute?

**Comment by Willsparker** [comment]
I think with the above PR, this issue can be closed. Any objections anyone?

**Comment by sxa** [comment]
Fine with me as long as we don't see lots of things queued up overnight because of it ;-)
