### ISSUE TITLE
Add s390x and ppcle64 architectures to RHEL, CENT, and SLES docker tasks

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#725]

**Comment by Willsparker** [comment]
ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1480  (Adding docker for RHEL7 PPC64le)

Note: I'll update this comment as I find solutions for each platform, and tick them off the table when (potential) solutions have been found.

|        | s390x | ppc64le |
|--------|-------|---------|
| RHEL   | :heavy_check_mark:    | :heavy_check_mark:|
| CentOS |       |        |
| SLES   |   :heavy_check_mark:     |         |

**SLES12/s390x:** (Tested on `test-marist-sles12-s390x-1`)
Package is called `docker`, in the `@System`, so, I think we can just add the `or ansible_architecture == "s390x"` check back to 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/176983e936cdf05f3f5e18a96d8b672ba91e1029/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml#L158
that was in the PR that #724 reverted.

**RHEL7/s390x:** (Untested due to lack of machine)
Docker have a repository for specifically RHEL, as opposed to CentOS, at `https://download.docker/linux/rhel/`, which appears to only have RHEL7/s390x in it. I think adding the repo and gpg key at that link, much like this is doing: 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/176983e936cdf05f3f5e18a96d8b672ba91e1029/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml#L116
should install `docker-ce`.

Apparently Docker provides static binaries for docker-engine, so we could use this to install docker on platforms that don't support docker, too. https://docs.docker.com/engine/install/binaries/

**Comment by Willsparker** [comment]
On advice from @sxa , I'm not going to add SLES12 ppc64le to the playbooks due to only having a single `SLES12` machine, and it being on `s390x`.

**Comment by sxa** [comment]
@jdekonin Are you happy with the above changes or do you want to do your own testing / addition for SLES/ppc64le?

**Comment by jdekonin** [comment]
These will break anyone that doesn't have the repos that contain docker setup for SLES.  It appears docker at least is not a default repo.  For my PPCLE cloud offering (Fyre) docker is there and this role works fine, but for my zLinux install docker is not present by default.  I think I'd lean towards not putting it in for SLES such that the playbook doesn't fail if the system isn't preconfigured as expected.

**Comment by Willsparker** [comment]
I'll remove that from the PR then :-)
