### ISSUE TITLE
Set up machine and appropriate CI jobs to run the new playbook testing scripts

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#865]
This will be putting any work from #842 and #864 into production kicked off via our CI tooling.
Will also require the installation of VM software (likely VirtualBox) onto one of our systems

**Comment by Willsparker** [comment]
To keep a log of the work being done :
- There's a consistent error when running the playbooks in parallel, in that (it seems) when one playbook fails (due to an external reason), the other ones with stop instantly and say `Connection to 127.0.0.1 closed by remote host`. Hypothesis that this is connected either to `vagrant halt` or `vagrant destroy`.
- The Windows section of the `testScript` will find the wrong IP address occasionally, due to the the way I put finding it into the script. As of #990 I believe this should work, however there are now issues of  previous runs leaving files around.
- Certain roles in (mainly) the unix playbook timing out : `ant-contrib`,`cmake`,`ccache`,`Nvidia-Cuda`

**Comment by Willsparker** [comment]
The `Connection to 127.0.0.1 closed by remote host` issue wasn't tied to either `vagrant halt` or `vagrant destroy`. It seems it is, however, tied to the multiple VMs running at once in some way - which is yet to be determined. A workaround for this has been to reduce the build executors on the Jenkins slave to 1, although this is not ideal as the job now takes ~8 hours to complete.
Another potential fix is to start the`testScript` in the Jenkins job to start at different times- This appeared to work in https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/52/ wherein the failed OSs were due to timeout or unresponsive network issues.

The timeouts didn't occur when running a single playbook at once, either- though this may just be luck.

**Comment by Willsparker** [comment]
<img width="382" alt="Screenshot 2019-11-15 at 13 22 19" src="https://user-images.githubusercontent.com/52783864/68946509-1157f300-07ab-11ea-99cd-1b093e815712.png">

ayy

**Comment by karianna** [comment]
@Willsparker so this can be closed?

**Comment by sxa555** [comment]
@karianna I think he's added that image onto the wrong issue as that one is for Dockerfile regular testing - https://ci.adoptopenjdk.net/view/Tooling/job/SXA-DockerfileCheck/

Saying that, with the addition of the retry operations in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/995 we are probably very close to being able to close this - need a few more test runs and to re-enable the build/test operations within the script to validate not only that the playbooks work but that they work well enough to perform builds and execute tests.

We have the playbook for setting up a machine for this at https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/985 and now have a machine at https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/910 which can be used to run this in production.

Current job is on the tooling tab at https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/ and will have the `SXA-` prefix removed (at least) once it's as stable as it can be (which is also true for the dockercheckfile job referenced above!)

**Comment by Willsparker** [comment]
We're still hitting the `Connection to <IP_ADDRESS> closed by remote host` error on a lot of runs of the job.

Just FYI, For windows, the following error message occurs due to whatever is closing the VMs, as this is the error message that is printed when ansible can't connect to the VM. Therefore, it can be considered as Windows equivalent to `Connection closed by remote host` : 

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ConnectionError: HTTPSConnectionPool(host='<VM_IP_ADDRESS>', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff67278add0>: Failed to establish a new connection: [Errno 113] No route to host',))
```

**Comment by Willsparker** [comment]
I've gone down a new road that completely removes the `vagrant` commands, other than `vagrant up`, and will start the playbook by doing it much like it has to be done with the Windows VMs- executes `ansible-playbook` on the machine and then points it at the VM. With #999, `vmDestroy.sh` is ran before `testScript.sh` is run so the VMs are still being destroy and cleared off the machine, once a new instance of the job is running, unless `--retainVM` is not specified- then it will destroy at the end of `testScript.sh`, however we can't do this on the `SXA-PlaybookCheckParallel` job, as that may close the other VMs that may still be running.

Initial impressions seem okay- There have been a few run throughs where finishing (succeeded or failed) VMs don't cause the other VMs to close, however this may be a bit of a false positive as the issue seems to be intermittent. If this works-around the connection closed issue, the build and testJDK scripts will have to be called in the same way as the Windows VM too.

**Comment by sxa555** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1013
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/992 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/999 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1000 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1003 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1007 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1016 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1020 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1022 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1025 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1026 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1029 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1030 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1034 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1035 https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1040
Docs: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/993

**Comment by Willsparker** [comment]
I've got to the point where 4 playbooks are stable and consistently are building JDKs successfully . (running `testScript.sh -v $OS -u https://github.com/Willsparker/openjdk-infrastructure/tree/git_check` ) -  currently debugging the windows Playbook as it seems the `win_get_url` ansible module has started to corrupt downloads for some reason (#1039).

**Comment by Willsparker** [comment]
See : https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/187/

**Comment by Willsparker** [comment]
Further to the above update - the ansible Module itself is currently broken in Ansible 2.9.x. I have rolled back both Jenkins Machines to ansible 2.5.1 and now all the playbooks are stable, and the various linux OSs can build a JDK and test it. Now just to get Windows to build the JDK and test it - though I've ran into a problem where after the playbook has been ran, the shared folder between the VM and the host machine doesn't appear, unless `vagrant reload` is executed.
