### ISSUE TITLE
Failure to build native tests on AIX 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-infrastructure#921]
While trying to build system test on the Adopt AIX machines, we get the following error: 

```
[exec] make: Not a recognized flag: C
```
e.g. https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/285/console

Note the same test builds fine in the internal AIX machines. 

Doing some digging about the error, it appears that it will be caused if we are not using GNU make. 

We do have a system test requirement of having `GNU make 3.79 or later` https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/docs/build.md

**Comment by Mesbah-Alam** [comment]
@sxa555 - could you please check the make version used in the AIX machines at Adopt and ensure we have GNU make installed on them?

**Comment by Mesbah-Alam** [comment]
FYI @smlambert

**Comment by sxa555** [comment]
The default make in `/usr/bin` is a standard AIX make. `/usr/bin/gmake` is symlinked to `/opt/freeware/bin/make` so either chnage how it's invoked or set that first in your `PATH`

**Comment by Mesbah-Alam** [comment]
> either chnage how it's invoked or set that first in your PATH

@sxa555 - is this a special requirement on tests for Adopt AIX machines? The same test runs fine on all other platforms, and also on AIX in the internal machines.

**Comment by smlambert** [comment]
@sxa555 - reopening as we need help to understand the differences between the Adopt/OpenJ9/internal machine configuration.  I had understood they all are configured with Adopt playbooks, but those may not yet specifically create a standard spot for where to expect make/gmake.

We have testing running internally and at OpenJ9 AIX machines (able to compile native tests on AIX).  Is there a way to ensure a standard location for tools on machines via the playbooks?

**Comment by sxa555** [comment]
For reference:

- Up until about six months ago we did not have any fully working AIX playbooks so the machines would likely have been set up manually and therefore subject to differences depending on who did it
- I was instructed by @tellison not to work on OpenJ9 machine setup (when I was given Windows machines a while back) therefore I cannot personally do any work to look at or resolve this although I would of course be happy to do so
- As far as I am aware the AdoptOpenJDK machines are set up in the same way I would expect the playbooks to set up the machines
- The most recent AIX addition to the adoptopenjdk farm - https://ci.adoptopenjdk.net/computer/test-osuosl-ppc64-aix-71-1/ - was set up with the playbook, although it has some intermittent build/test issues, however that may be the only "master" source of the configuration defined by the playbooks.
- The `make` package (which provides GNU make via rpm/yum from the AIX toolbox) installs symlinks to make itself available as: `/usr/bin/gmake` `/usr/bin/gmake_32` `/usr/bin/gmake_64` `/usr/linux/bin/make` `/usr/linux/bin/make_32` `/usr/linux/bin/make_64` as well as all the `make`/`gmake` alternatives sitting in `/opt/freeware/bin` where it's really installed. If other machines are set up differently, it has likely been done over and above the standard installation machanism for AIX in order to work. On that basis my preferred solution is as per my previous comment.

Regarding the last point, it has always been my view in order to avoid masking issues that could occur on an end-user's machine (especially critical if we intend to support commercial use of things we're producing) I personally don't want to change the default `PATH`s on the machines or adjust the default tools unless absolutely necessary (for example the changes we've made to make `/usr/bin/java` point to an adoptopenjdk8 build so that something is available as `java` on the machine).

**Comment by jdekonin** [comment]
The [playbook](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/0dce2952c50e3d886ec84e753ec2723c0531bd7c/ansible/playbooks/aix.yml#L194) installs make via yum ( via AIX Toolbox for Linux Applications ) which adds packages into `/opt/freeware`  

`/opt/freeware/bin` is first on the PATH as modified via [PR #118](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/118) Feb 2018.

On the OpenJ9 machines `/opt/freeware/bin/gmake` is a symlink to `/opt/freeware/bin/make`, which I have no idea how it got there I assume via installed dependency or maybe its added with the make install???

**Comment by smlambert** [comment]
All of these explanations are very helpful, thanks @sxa555 and @jdekonin 

I will close this for now as we decide how best to handle the differences so that tests can be run.

**Comment by sxa555** [comment]
@jdekonin I suspect the make rpm put that symlink in place
