### ISSUE TITLE
Tests fail to run on build-osuosl-ppc64-aix-71-2

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#963]
Tests are not starting on build-osuosl-ppc64-aix-71-2.
The last message is
```
13:37:32  unzip file: OpenJDK8U-jdk_ppc64_aix_openj9_8u232b09_openj9-0.17.0.tar.gz ...
13:37:35  unzip file: OpenJDK8U-jre_ppc64_aix_openj9_8u232b09_openj9-0.17.0.tar.gz ...
13:37:37  0481-014 chmod: not all requested changes were made to j2sdk-image
```
so it looks like there is an issue installing the jdk under test.
The chmod message is not seen on successful test runs on the other aix build machine, build-osuosl-ppc64-aix-71-1

Sample job: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/5/console

**Comment by karianna** [comment]
The workspace was deleted after the run so I can't see what the permissions looked like :-(.

**Comment by lumpfish** [comment]
It was happening for every test run at unzipping the sdk time, so if someone could log in as Jenkins and simulate that, maybe that would show us what's going on.  Perhaps a run of something first to confirm it's still happening?

**Comment by sxa555** [comment]
This is caused by the directory that we are extracting to having the SGID bit set.

But glossing over that for a second, @smlambert why are we running `chmod -R 755` on  the SDK directory after extracting it in get.sh? Surely the contents of the tarball should have the correct permissions, and doing something like this can only mask potential problems with the permissions within the tarball? @Mesbah-Alam it looks like you added this in https://github.com/AdoptOpenJDK/openjdk-tests/pull/459/files
